.nowignore, now.json, src/components/NotePage/NoteList/NoteItem.tsx, src/components/SideNavigator/SideNavigator.tsx, src/components/SideNavigator/StorageItem/FolderItem.tsx, src/components/SideNavigator/StorageItem/StorageItem.tsx, src/lib/db/store.ts, src/lib/router/utils.ts, webpack.config.ts
- added `.nowignore` file
- added necessary routes to `now.config`
- updated all links to include `/app` prefix
- updates `useNotesPathname` to remove `/app` prefix before processing.
=> Path change

src/lib/db/store.spec.ts, src/lib/db/store.ts
=> remove trashed note from tagMap and folderMap id sets

package-lock.json, package.json, webpack.config.ts
Added `Dotenv` webpack plugin [site](https://github.com/mrsteele/dotenv-webpack)
- Loads env variables from designated file (default `.env`)
- Only loads env variables which are referenced
=> added Dotenv webpack plugin

package-lock.json, package.json, src/components/Storage/StorageEdit.tsx, src/components/atoms/LoginButton.tsx
- Fixed `useCallback` deps
- added `env-cmd` to dev deps
=> Callback dep fix

src/components/Storage/CloudStorageSelector.tsx, src/lib/accounts/users.ts
Refresh button for cloud storage list
=> refresh button for cloud storage info

package-lock.json, package.json, src/components/NotePage/NoteDetail/NoteDetail.tsx, typings/styled-components.d.ts
Use custom definitions for styled-components
=> Styled component types

package-lock.json, package.json, src/components/NotePage/NotePage.tsx, src/components/atoms/FileDropZone.tsx, src/lib/legacy-import.ts, src/lib/utils/files.ts
- Drag previous Boostnote `xxxx.cson` files onto folders `NoteList` component.
- Uses forked version of `cson-parser` using coffeescript 2
=> Import old

now.json
- all none static routes to index.html
=> correct routing for static

src/components/NotePage/NoteList/NoteItem.tsx, src/components/NotePage/NoteList/NoteList.tsx, src/components/NotePage/NotePage.tsx
Reverts BoostIO/BoostNote.next#126
=> Revert "Fix/search notes"

src/components/NotePage/NoteDetail/NoteDetail.tsx, src/components/NotePage/NotePage.tsx, src/components/atoms/ToolbarExportButton.tsx
https://gyazo.com/4ec5c6d74ff2819d7250983bc9047b79
=> display note from subfolders in note list

src/components/Storage/StorageEdit.tsx
Added the modal for delete a storage at storage setting page.
=> Added the modal for delete a storage

src/components/PreferencesModal/styled.tsx, src/components/Storage/StorageCreate.tsx, src/components/Storage/StorageEdit.tsx
- Create storage page
- Edit storage page
=> Fixed UI of storage pages

src/components/SideNavigator/SideNavigatorItem.tsx
=> Fixed the style for folder name

package-lock.json, src/components/NotePage/NotePage.tsx, src/components/PreferencesModal/ImportTab.tsx, src/components/PreferencesModal/PreferencesModal.tsx, src/components/atoms/FileDropZone.tsx, src/lib/legacy-import.ts
Import page for old data in preferences modal.
=> Old data import page

package-lock.json, src/components/App.tsx, src/components/PreferencesModal/GeneralTab.tsx, src/components/SideNavigator/SideNavigator.tsx, src/lib/i18n/enUS.ts, src/lib/i18n/ja.ts, src/lib/preferences/types.ts, src/lib/preview.ts, src/lib/styled/themes/solarizedDark.ts
We have another theme called "Solarized Dark"!
=> Added solarized dark

src/components/PreferencesModal/ImportTab.tsx, src/components/PreferencesModal/styled.tsx
=> Fix UI of import note at Preferences

package-lock.json, package.json, src/components/NotePage/NoteList/NoteItem.tsx
=> update note date

src/components/SideNavigator/FolderListFragment.tsx
for 
> Add the sub-folder create button on the default folder @Davy Castel 
https://www.notion.so/boostio/2069b7057f4b436bac3ad5300a85eb27?v=c6a532520ca84175989b7828cd8b536c&p=ef6a3af592514ad5bbf37e7810380b23
=> add folder create button on notes file

src/components/NotePage/NoteDetail/NoteDetail.tsx, src/components/NotePage/NotePage.tsx, src/components/Tutorials/TutorialsNoteDetail.tsx, src/components/Tutorials/TutorialsPage.tsx, src/lib/generalStatus/store.ts, src/lib/generalStatus/types.ts
- Add a button for split view
from 
https://www.notion.so/boostio/2069b7057f4b436bac3ad5300a85eb27?v=c6a532520ca84175989b7828cd8b536c&p=ef6a3af592514ad5bbf37e7810380b23
result:
https://gyazo.com/bb58cbcb94925574b42d4c19069e3b94
=> Simplifying View modes

src/components/NotePage/NoteDetail/TagList.tsx, src/components/NotePage/NoteList/NoteItem.tsx
=> Fixed tag UI

webpack.config.ts
Moved Terser config into production only to tackle out of memory issues.
=> fixed bug causing memory issues

src/components/NotePage/NoteList/NoteItem.tsx, src/components/NotePage/NoteList/NoteList.tsx, src/components/NotePage/NotePage.tsx, src/lib/styled/index.ts, src/lib/styled/keyframes.ts, typings/styled-components.d.ts
for
> Open link in another tab [link](https://boostnote.io)
https://www.notion.so/boostio/2069b7057f4b436bac3ad5300a85eb27?v=c6a532520ca84175989b7828cd8b536c&p=ef6a3af592514ad5bbf37e7810380b23
Result:
[https://gyazo.com/569b19d505ad12bf4372941df01b61aa](https://gyazo.com/569b19d505ad12bf4372941df01b61aa)
=> animation for new note item

src/components/PreferencesModal/BillingTab.tsx
- Check user subscription status
- Display sign in if not signed in
- Display Upgrade if not paying sub
- Display manage otherwise
=> updated billing ux

src/components/Toast/ToastItem.tsx, src/components/Toast/ToastList.tsx
https://gyazo.com/ba030ec6d2cbd7cc6455ab0562ce5ad8
=> fix toast item

src/components/SideNavigator/SideNavigator.tsx, src/components/SideNavigator/TagListFragment.tsx
- trash can renamed to trash
- remove folded icon when no tags in tag list
=> side navigator small fix

index.html
- fixed typo
- should fix login issue
=> fixed open external ref

src/components/PreferencesModal/BillingTab.tsx
- converted href to `openNew` in billing page
=> fixed external links in billing

now.json, webpack.config.ts
- added public path for non-election build based on `process.env.TARGET`
- stricter now route regex
=> added publicPath for non-electron build

src/components/Router.tsx
While analyzing this project, I found it out an unused break.
=> removed dummy break

CONTRIBUTING.md
Fixed the link address and made the hyperlink worked properly.
=> Edit CONTRIBUTING.MD

src/components/NotePage/NoteDetail/NoteDetail.tsx, src/components/NotePage/NoteList/NoteList.tsx, src/components/SideNavigator/SideNavigator.tsx, src/components/SideNavigator/SideNavigatorItem.tsx, src/lib/styled/styleFunctions.ts
=> Adjusted Colors, Sizes, and Spacing for Each Icon

src/components/SideNavigator/ControlButton.tsx, src/components/SideNavigator/SideNavigator.tsx, src/components/SideNavigator/SideNavigatorItem.tsx, src/components/atoms/ButtonIcon.tsx
=> Adjusted Spacing on Sidebar

src/components/SideNavigator/SideNavigator.tsx, src/components/SideNavigator/SideNavigatorItem.tsx
=> Styled sidebar

src/components/NotePage/NoteList/NoteList.tsx, src/components/NotePage/NotePage.tsx
- added filtering to `NoteList`
- removed default filtering in `NotePage`
- adjusted `NoteList` props to use `currentNoteId` instead of `currentNoteIndex` to stop sync bugs.
=> filter by updatedAt, createdAd, title

src/components/NotePage/NoteList/NoteList.tsx, src/components/NotePage/NotePage.tsx
I've got some errors when I created new storage.
And I fixed it.
=> fixed error when creating a new storage because there were no current note

src/components/atoms/MarkdownPreviewer.tsx
=> fixed 229 issue that checkbox dosen't check

src/components/PreferencesModal/GeneralTab.tsx, src/lib/i18n/esEs.ts, src/lib/i18n/index.ts, src/lib/preferences/types.ts
Added Spainsh (Spain) transalation to all words, and make it ready to use.
=> Add Spanish (Spain) translation.

app/index.js, src/components/NotePage/NoteDetail/NoteDetail.tsx, src/components/NotePage/NoteList/NoteList.tsx, src/components/SideNavigator/SideNavigator.tsx
=> Hide titlebar for macOS

src/components/NotePage/NoteDetail/NoteDetail.tsx, src/components/NotePage/NotePage.tsx, src/lib/events.ts
Fix https://github.com/BoostIO/BoostNote.next/issues/218
=> Fix title focus issue

src/components/PreferencesModal/GeneralTab.tsx, src/lib/i18n/index.ts, src/lib/i18n/ko.ts, src/lib/preferences/types.ts
Added Korean translation to all words, and make it ready to use.
Please check it out and if you find weird parts, let me know.
=> Added Korean translation. (#228)

src/components/NotePage/NoteList/NoteList.tsx, src/components/NotePage/NotePage.tsx, src/lib/keyboard.ts
=> Fix delete shortcut

src/components/SideNavigator/SideNavigator.tsx
=> Fix no storage label

src/components/NotePage/NoteList/NoteItem.tsx
I tried following steps with BoostNote App.
1. Select Trashed Tab
2. Select a Trashed Note and then right click(Open menu)
3. Select Delete button
but I didn't see any reaction from BoosNote😞
Show messageBox when delete trashedNote🗑(like select trash icon)
If you select `Delete a Note`, the note is purged.
CurrentNote is not affect by my implementation.
=> Show messageBox when delete trashedNote

src/components/NotePage/NoteDetail/NoteDetail.tsx
Should not add same tag if same tag is added already
=> Should not add same tag if same tag is added already

src/components/NotePage/NoteDetail/NoteDetail.tsx
=> Fix NoteDetail button layout

tsconfig-webpack.json, tsconfig.json, webpack.config.ts
=> Show app version

app/menu.js
=> Show check for updates always

src/components/App.tsx, src/components/NotePage/NoteList/NoteItem.tsx, src/components/NotePage/NoteList/NoteList.tsx, src/components/NotePage/NotePage.tsx, src/components/SideNavigator/FolderListFragment.tsx, src/components/SideNavigator/SideNavigator.tsx, src/components/SideNavigator/SideNavigatorItem.tsx, src/components/SideNavigator/TagListFragment.tsx, src/lib/db/NoteDb.spec.ts, src/lib/db/NoteDb.ts, src/lib/db/specs/renameFolder.spec.ts, src/lib/db/store.spec.ts, src/lib/db/store.ts, src/lib/db/utils.ts
=> Rollback root folder

src/lib/i18n/zhHK.ts, src/lib/i18n/zhTW.ts
=> add translation

src/components/SideNavigator/SideNavigator.tsx, src/lib/generalStatus.ts, src/lib/nav.ts, src/lib/specs/nav.spec.ts
when I created new folder with storage folded, It is difficult to tell whether it was created😞
It is desirable to select the folder I created
- itemIdListToOpen push storageID
- Add getStorageItemId
- Add nav.spec.ts
=> Open the created folder always when created folder

package-lock.json, src/components/SideNavigator/SideNavigator.tsx
Display more useful message when sync fails due to usage limit.
=> storage usage limit reached message

src/locales/de.ts, src/locales/enUS.ts, src/locales/esEs.ts, src/locales/ja.ts, src/locales/ko.ts, src/locales/ptBR.ts, src/locales/ukUA.ts, src/locales/zhCN.ts, src/locales/zhHK.ts, src/locales/zhTW.ts
Fixed the word about the mobile app of locales.
iOS : https://apps.apple.com/us/app/boostnote-mobile/id1498182749
Android : https://play.google.com/store/apps/details?id=com.boostio.boostnote
=> Fixed the word of locales

src/components/atoms/MarkdownPreviewer.tsx
=> Fix emoji plugin

src/components/atoms/NavigatorHeader.tsx, src/components/atoms/NavigatorItem.tsx, src/components/molecules/StorageNavigatorFragment.tsx, src/lib/styled/styleFunctions.ts
=> Fix nav labels

src/components/pages/StorageEditPage.tsx, src/locales/de.ts, src/locales/enUS.ts, src/locales/esES.ts, src/locales/frFR.ts, src/locales/ja.ts, src/locales/ko.ts, src/locales/ptBR.ts, src/locales/ukUA.ts, src/locales/zhCN.ts, src/locales/zhHK.ts, src/locales/zhTW.ts
Changes `Remove` to `Delete` Storage.
- Fixes Issue #434 
Other localization languages needs update due to this change.
=> Updated remove storage strings

src/electron/index.ts
Implemented single instance lock through `app.requestSingleInstanceLock()`
Not really knowledgeable in TypeScript so it might need revision, but nonetheless gets the job done.
- Fixes issue #440
=> Implemented 'single-instance' lock

src/locales/de.ts
https://github.com/BoostIO/BoostNote.next/pull/446
=> rephrased storage.delete in de.ts

src/components/PreferencesModal/GeneralTab.tsx, src/lib/i18n.ts, src/lib/preferences.ts, src/locales/itIT.ts
#228 added italian language 
it-IT
=> Added Italian Language

homepage/locales/fr.ts
#462
Add french translation for the new homepage.
=> Homepage French translation

homepage/components/organisms/Header.tsx, homepage/lib/i18n.ts, homepage/locales/de.ts
As noticed in https://github.com/BoostIO/BoostNote.next/issues/462#issuecomment-625376038 this might need a change when I know exactly what it means.
Otherwise, open for discussion / improvements.
=> Homepage German localisation

src/components/pages/NotePage.tsx
=> Fix redirection after note creation

readme.md
Improve spelling, grammar, commas, capitalization
In addition, spell out the abbreviations "deps" and "TBA" for a lower barrier.
=> Slightly improve readme.md file

homepage/components/organisms/Header.tsx, homepage/lib/i18n.ts, homepage/locales/vn.ts
This PR add Vietnamese translation for homepage
=> added Vietnamese translation for homepage

package.json, src/components/atoms/MarkdownPreviewer.tsx, src/components/atoms/markdown/CodeFence.tsx
=> Add copy button to codefence

src/components/atoms/MarkdownPreviewer.tsx
=> Allow some html tags available in github

readme.md, scripts/dev-electron.ts
Fix `npm run dev:electron` in Windows.
=> Fix dev script win

src/components/atoms/CodeEditor.tsx, src/components/atoms/CustomizedCodeEditor.tsx, src/components/organisms/NoteDetail.tsx, src/lib/db/FSNoteDb.ts, src/lib/db/PouchNoteDb.ts, src/lib/dnd.ts, src/lib/dom.ts, src/lib/string.ts
Fixes https://github.com/BoostIO/BoostNote.next/issues/468
- Improve drop image
- Accept paste event with image data
=> Fix image drop

homepage/locales/nl.ts
Updated and added missing Dutch translations for the homepage
See #462
=> chore: Update Dutch homepage locale (#462)

src/components/organisms/ImportLegacyNotesForm.tsx
=> Normalize legacy folder name

src/components/molecules/StorageNavigatorItem.tsx, src/components/organisms/AppNavigator.tsx, src/lib/styled/BaseTheme.ts, src/lib/styled/styleFunctions.ts, src/themes/dark.ts, src/themes/legacy.ts, src/themes/light.ts, src/themes/sepia.ts, src/themes/solarizedDark.ts
- Adjusted secondary button styles of each theme
- Adjusted font-sizes of the app navigators
=> UI: Adjusted Styling of the App Navigator

src/components/atoms/markdown/MarkdownCheckbox.tsx
=> fixed checkbox losing the ability to untoggle when using an uppercase X

src/components/atoms/TagNavigatorListItem.tsx
This was the issue:
Fixed it like this:
Is that ok?
=> Fix: Tag text wrapping on window resize

package-lock.json, package.json, src/components/atoms/MarkdownPreviewer.tsx, src/lib/platform.ts, typings/unified.d.ts
Add support for internal header links in notes preview.
Solves #622
=> feat: internal heading links

homepage/components/organisms/Header.tsx, homepage/lib/i18n.ts, homepage/locales/tr.ts
Homepage Turkish translations for PR #462 🇹🇷
=> Homepage Turkish Translations (#462)

.babelrc, .storybook/main.js, .storybook/preview.js, package-lock.json, package.json, src/components/App.tsx, src/stories/Button.stories.tsx, src/stories/utils/themes.tsx, src/themes/index.ts
* Partially refactor `atoms/form.tsx`
* Initiate a storybook project and add stories about `atoms/Form/Button, CheckItem, Heading`
=> Initiate BoostNote storybook

src/locales/ruRU.ts
ImportTab section was missing translation in row 170
=> Updated RU localization

build-utils/afterSignHook.js, macOs/entitlements.mac.plist, package-lock.json, package.json
=> Notarize after code signing

package-lock.json, package.json, src/components/App.tsx, src/components/PreferencesModal/PreferencesModal.tsx, src/components/Router.tsx, src/components/atoms/BoostHubWebview.tsx, src/components/molecules/NotePageToolbarNoteHeader.tsx, src/components/molecules/SearchModalNoteResultItem.tsx, src/components/molecules/StorageNavigatorFragment.tsx, src/components/organisms/BoostHubIntroModal.tsx, src/components/organisms/BoostHubSignInForm.tsx, src/components/organisms/NoteDetail.tsx, src/components/organisms/NotePageToolbar.tsx, src/components/organisms/NoteStorageNavigator.tsx, src/components/pages/BoostHubTeamsShowPage.tsx, src/components/pages/NotePage.tsx, src/components/pages/WikiNotePage.tsx, src/electron/ipc.ts, src/electron/menu.ts, src/lib/dom.ts, src/lib/electronOnly.ts, src/lib/events.ts, src/lib/exports.ts, src/lib/protocol.ts, src/lib/string.ts, src/mobile/components/molecules/StorageNavigatorFragment.tsx, src/mobile/components/organisms/NoteDetail.tsx, src/mobile/components/pages/NotePage.tsx, static/main-preload.js
=> Fix key bindings

src/components/atoms/FolderTreeListItem.tsx, src/components/atoms/NavigatorItem.tsx, src/components/atoms/TagNavigatorNewTagPopup.tsx, src/components/molecules/BookmarkNavigatorFragment.tsx, src/components/molecules/FolderDetailListFolderItem.tsx, src/components/molecules/FolderDetailListNoteItem.tsx, src/components/molecules/FolderNavigatorItem.tsx, src/components/molecules/NoteNavigatorItem.tsx, src/components/molecules/NotePageToolbarFolderHeader.tsx, src/components/molecules/NotePageToolbarNoteHeader.tsx, src/components/molecules/SearchModalNoteResultItem.tsx, src/components/molecules/TagListFragment.tsx, src/components/organisms/NoteStorageNavigator.tsx, src/components/organisms/SearchModal.tsx, src/components/organisms/TagDetail.tsx, src/mobile/components/molecules/FolderListFragment.tsx, src/mobile/components/molecules/TagListFragment.tsx, src/mobile/components/pages/NotePage.tsx, src/themes/dark.ts
I restyled the sidebar to make it look the same as the current team version of Boost Note.
=> UI: Adjusted Styles of the Sidebar to Make It Look Same with Team Version

src/components/organisms/NoteStorageNavigator.tsx, src/themes/dark.ts
I adjusted some styles of the storage switcher to make it look the same as the team version.
| ![image](https://user-images.githubusercontent.com/2410692/104808611-cc09d800-582a-11eb-9a19-ab4e08222378.png) | ![image](https://user-images.githubusercontent.com/2410692/104808594-b1cffa00-582a-11eb-9aea-fc58cd8d27df.png) |
=> UI: Adjusted Styling of the Storage Switcher

src/components/atoms/BoostHubWebview.tsx, src/components/organisms/NoteStorageNavigator.tsx
Added `Toggle App Navigator` button to context menu in boosthub
=> add app navigator toggle button to booshub webview context menu

src/cloud/pages/shared/[link].tsx
Allow router to handle realtime server connection
=> handle collaboration connection in router

src/cloud/components/organisms/settings/UpgradeTab.tsx
I updated the upgrade tab in the settings modal based on the info I was provided.
| ![CleanShot 2021-02-19 at 17 00 18](https://user-images.githubusercontent.com/2410692/108475819-91d1a180-72d4-11eb-933e-241722506aca.png) | ![CleanShot 2021-02-19 at 17 02 08](https://user-images.githubusercontent.com/2410692/108475867-a4e47180-72d4-11eb-883d-f88099f1b036.png) |
=> UI: Updated Upgrade Tab

src/cloud/pages/[teamId]/timeline.tsx
I added some space and adjusted the alignment of the top bar on the timeline page.
| ![CleanShot 2021-03-05 at 16 26 09](https://user-images.githubusercontent.com/2410692/110082365-96b44c00-7dd0-11eb-8393-3f8d152a10ca.png) | ![CleanShot 2021-03-05 at 16 31 36](https://user-images.githubusercontent.com/2410692/110082390-9fa51d80-7dd0-11eb-91e4-d1a0afcdb627.png) |
=> UI: Adjusted Timeline Top Bar

src/lib/migrate.ts
Filter out trashed notes in migration.
=> filter out trashed docs for migration

src/cloud/api/teams/subscription/index.ts, src/lib/migrate.ts
=> simple coupon get

src/cloud/components/organisms/settings/MembersTab.tsx
I adjusted the styling of the guest tab in the preferences modal.
| ![CleanShot 2021-03-08 at 14 14 54](https://user-images.githubusercontent.com/2410692/110278385-7d9edb80-801a-11eb-9dd7-f8704706ee66.png) | ![CleanShot 2021-03-08 at 14 25 40](https://user-images.githubusercontent.com/2410692/110278412-8d1e2480-801a-11eb-8e8a-e7d60019a3cc.png) |
=> UI: Adjusted Styling of the Guest Tab in Preferences

src/components/PreferencesModal/MigrationTab.tsx, src/components/atoms/ProgressBar.tsx, src/index.tsx, src/lib/migrate/index.ts, src/lib/migrate/store.ts
Allow migrations to run in the background
=> allow migrations to run in the background

src/cloud/components/organisms/RightSideTopBar/styled.ts, src/components/atoms/BoostHubWebview.tsx
- Added a draggable area on top of the cloud space webview
- The area will bypass all mouse inputs to the webview
=> Fix draggable area of cloud space

src/cloud/components/organisms/Modal/contents/Workspace/WorkspaceModalForm.tsx, src/cloud/components/organisms/Modal/contents/styled.ts
I adjusted the header styles of the "Create a Workspace" modal to make it more readable.
| ![CleanShot 2021-03-19 at 15 35 27](https://user-images.githubusercontent.com/2410692/111742415-7e155d00-88cb-11eb-9ef9-e7f23d8f9c7c.png) | ![CleanShot 2021-03-19 at 15 53 15](https://user-images.githubusercontent.com/2410692/111742434-853c6b00-88cb-11eb-9ead-0c02427e216c.png) |
=> UI: Restyled Create Workspace Modal

src/cloud/components/molecules/Editor/index.tsx, src/cloud/lib/router.ts, src/cloud/lib/stores/nav/store.tsx
=> Use state instead of query

src/components/v2/organisms/Sidebar/molecules/SidebarTree.tsx
I adjusted the alignments of the buttons :)
| <img width="153" alt="Screen Shot 2021-04-21 at 12 12 18 PM" src="https://user-images.githubusercontent.com/2410692/115828631-f205d080-a448-11eb-9547-d806f2cfef14.png"> | ![CleanShot 2021-04-23 at 15 27 34](https://user-images.githubusercontent.com/2410692/115828678-ffbb5600-a448-11eb-9d43-c65b040bc783.png) |
=> UI: Adjusted Alignments of the Sidebar Buttons

src/components/organisms/AppNavigator.tsx, src/components/organisms/BoostHubSignInForm.tsx
- Re-add local space create link to onboarding
- Add cloud space info button to local AppNav
=> Local cloud space intro

src/components/PreferencesModal/MigrationTab.tsx, src/components/organisms/CloudIntroModal.tsx
Add coupon notifications to cloud into page, migration page and migration complete page
=> Local migrate coupon

src/cloud/components/molecules/Editor/EditorIndentationStatus.tsx, src/cloud/components/molecules/Editor/EditorKeyMapSelect.tsx, src/cloud/components/molecules/Editor/EditorThemeSelect.tsx
I changed them a bit bigger than before to make them readable.
| ![CleanShot 2021-05-01 at 13 21 58](https://user-images.githubusercontent.com/2410692/116771494-e50b6180-aa86-11eb-8323-ab7df4314f87.png) | ![CleanShot 2021-05-01 at 14 05 58](https://user-images.githubusercontent.com/2410692/116771498-ed639c80-aa86-11eb-9a6d-dea48383e3a0.png) |
=> UI: Changed Editor Setting Font Sizes

src/cloud/components/Application.tsx, src/shared/components/organisms/Sidebar/atoms/SidebarTreeItem.tsx, src/shared/components/organisms/Sidebar/molecules/SidebarTree.tsx
I adjusted the alignment and sizes of the side nav to make it closer to the mockup.
| ![CleanShot 2021-05-01 at 15 12 00](https://user-images.githubusercontent.com/2410692/116773397-23594e80-aa90-11eb-88db-d603d85b0fd3.png) | ![CleanShot 2021-05-01 at 15 09 42](https://user-images.githubusercontent.com/2410692/116773404-2e13e380-aa90-11eb-8241-1c870adba62c.png) |
=> UI: Adjusted Side Nav Alignment & Sizes

src/cloud/interfaces/analytics/mixpanel.ts
analytics events for `ComentThreads` & `Comments`
=> comment mixpanel events

src/cloud/components/molecules/ThreadItem.tsx, src/cloud/components/organisms/CommentManager.tsx
=> change ui in line with spec

src/cloud/components/App.tsx, static/boosthub-preload.js
Add stopPropagation to App.tsx in cloud
Add stopPropagation to boosthub-preload static script
=> Fix context menu setup in boosthub

src/components/organisms/NoteDetail.tsx, src/components/organisms/SearchModal.tsx, src/components/pages/WikiNotePage.tsx, src/lib/generalStatus.ts
**Update cursor and focus handling for NoteDetail**
Fix cursor position handling (remember across view modes)
Fix cursor update from global search (use generalStatus)
Fix changing view mode does not copy markers from serach dialog
This should resolve #755 and additionaly local search not marking found items after view mode change.
=> Update cursor and focus handling for NoteDetail

src/lib/v2/mappers/local/sidebarTree.tsx
Now they are presorted when sorting their children
=> Fix workspace sorting order

src/lib/v2/mappers/local/sidebarTree.tsx
Fix deleting folder leaves archived notes in workspace
=> Fix delete folder archives notes and they show up in workspace

src/cloud/components/organisms/DocPage/SharedDocPage.tsx
- Show title of the document
- Adjusted styling of the title
=> UI: Show Title on Shared Page

src/cloud/components/molecules/ContentManager/Actions/ContentManagerBulkActions.tsx, src/cloud/components/molecules/ContentManager/Rows/ContentManagerDocRow.tsx, src/cloud/components/molecules/ContentManager/Rows/ContentManagerRow.tsx, src/cloud/components/molecules/ContentManager/Rows/EmptyRow.tsx, src/cloud/components/molecules/ContentManager/SortingOption.tsx, src/cloud/components/molecules/ContentManager/index.tsx, src/cloud/components/molecules/ContentManager/styled.ts, src/cloud/components/organisms/Topbar/Controls/ControlsContextMenu/ControlsContextMenuItem.tsx, src/cloud/components/organisms/Topbar/Controls/ControlsContextMenu/FolderContextMenu.tsx, src/cloud/components/organisms/Topbar/Controls/ControlsContextMenu/styled.ts
- Applied new context menu styles to **sorting options menu** and folder **context menu**
- Changed from archive button to delete button on checked doc menu
- Expand border and background to full width on Folder/Workspace/Label/Shared Pages
| ![Menu_Before](https://user-images.githubusercontent.com/2410692/121868283-c3ff8700-cd3b-11eb-9d11-852e0513ff04.png) ![Sort_Before](https://user-images.githubusercontent.com/2410692/121868302-c95cd180-cd3b-11eb-8664-fbb113ebe1f8.png) | ![Menu_After](https://user-images.githubusercontent.com/2410692/121868356-d8438400-cd3b-11eb-9141-3a507f310bc6.png) ![Sort_After](https://user-images.githubusercontent.com/2410692/121868392-e42f4600-cd3b-11eb-9184-b8863dde3e0b.png) |
| …
=> UI: Improve Folder/Workspace/Label/Shared Pages

src/shared/components/atoms/GlobalStyle.tsx
Fixed default table background colors for local space tables
=> Fix default table background color missing in globla style

src/components/App.tsx, src/components/organisms/AppNavigator.tsx, src/lib/boosthub.tsx, src/lib/generalStatus.ts
Hide notification icon in personal teams
=> add  to global data types

src/cloud/components/organisms/Modal/contents/Import/ImportModalGuide.tsx, src/cloud/lib/i18n/enUS.ts, src/locales/enUS.ts
I replaced `Boost Note for Teams` with `Boost Note` :)
=> UI: Boost Note for Teams -> Boost Note

src/cloud/lib/comments/index.ts
- Fix broken mention display
- Fix mention node construction in comment editing
=> better mention parsing from comment

src/cloud/components/molecules/ContentManager/Rows/ContentManagerRow.tsx, src/shared/components/organisms/Topbar/atoms/TopbarTreeItem.tsx, src/shared/components/organisms/Topbar/molecules/TopbarBreadcrumb.tsx
change icon colors in CM and topbar
=> Icon colors

src/cloud/components/Application.tsx, src/components/organisms/SidebarContainer.tsx
=> fix rendering sidebar

src/lib/v2/mappers/local/sidebarTree.tsx
Fix issue: https://github.com/BoostIO/BoostNote.next/issues/1047
=> Fix folders and files are sorted together.

src/electron/updater.ts
Like `Found Updates` ->  `Found Updates - Boost Note`.
Closes #735
=> Append Boost Note to dialog title

src/cloud/components/HelpLink.tsx, src/cloud/components/Modal/InviteMembers/InviteMemberModalSection.tsx, src/cloud/components/Modal/InviteMembers/InviteMembersModal.tsx, src/cloud/components/OpenInviteSection.tsx, src/cloud/components/buttons/InviteCTAButton.tsx, src/cloud/lib/i18n/enUS.ts, src/cloud/lib/i18n/fr.ts, src/cloud/lib/i18n/ja.ts, src/cloud/lib/i18n/types.ts, src/cloud/lib/i18n/zhCN.ts
https://github.com/BoostIO/BoostNote.next/pull/1102
=> Invite modal improvements

src/cloud/components/Editor/index.tsx, src/cloud/components/settings/UserPreferencesForm.tsx, src/cloud/lib/i18n/enUS.ts, src/cloud/lib/i18n/fr.ts, src/cloud/lib/i18n/ja.ts, src/cloud/lib/i18n/types.ts, src/cloud/lib/i18n/zhCN.ts, src/cloud/lib/stores/settings/store.ts, src/cloud/lib/stores/settings/types.ts
Add optional rendering of the editor toolbar
Add user setting for editor toolbar show/hide
Add translations
Tested in desktop and web app
Showcase:
https://user-images.githubusercontent.com/18196945/131153149-836d7cda-b43a-4f4e-ad21-4d4e8baf59e5.mp4
=> Add optional editor toolbar

src/cloud/components/Application.tsx, src/cloud/components/molecules/PageSearch/InPageSearchPortal.tsx, src/cloud/lib/shortcuts.ts, src/cloud/lib/stores/electron.ts, src/design/components/atoms/GlobalStyle.tsx, src/lib/electronOnly.ts, static/boosthub-preload.js
Add search portal
Add search components
Add search logic and API call
Implement search UI and styling
Add left/right actions (next/previous) and events
Add hack for hide/show input on search (hide elements)
Showcase:
https://user-images.githubusercontent.com/18196945/131561521-6e48c72c-47f1-4f59-a329-cd118c8c94ee.mp4
Showcase with focus:
Uploading 2021-09-01 20-52-32.mp4…
=> Add in page search

src/cloud/components/Application.tsx, src/cloud/components/DocPage/DocPageHeader.tsx, src/cloud/components/ViewerDisclaimer.tsx, src/cloud/components/buttons/InviteCTAButton.tsx, src/cloud/lib/i18n/enUS.ts, src/cloud/lib/i18n/fr.ts, src/cloud/lib/i18n/ja.ts, src/cloud/lib/i18n/types.ts, src/cloud/lib/i18n/zhCN.ts
Add translations for all strings
Remove ask to edit from invite CTA handler
Remove sidenav viewer alert
Add alert on each doc
Showcase:
Fixes: https://github.com/Boostnote/BoostHub/issues/1334
=> Improve viewer alert

src/cloud/components/DocProperties/DocAssigneeSelect.tsx, src/cloud/lib/i18n/enUS.ts, src/cloud/lib/i18n/fr.ts, src/cloud/lib/i18n/ja.ts, src/cloud/lib/i18n/types.ts, src/cloud/lib/i18n/zhCN.ts
Add invite button before search selection list for doc assign
Add translations for button title
Showcase:
Tested in Web app and desktop app
Fixes: https://github.com/Boostnote/BoostHub/issues/1318
=> Add invite button in doc assign section

src/cloud/components/ViewerDisclaimer.tsx
=> Fix Viewer alert UI

src/cloud/components/Application.tsx, src/cloud/lib/shortcuts.ts
https://intercom.help/boostnote-for-teams/en/articles/4347206-keyboard-shortcuts
=> shortcut for sidebar

src/cloud/components/DocPage/DocPageHeader.tsx, src/cloud/components/Props/Pickers/DueDateSelect.tsx, src/cloud/components/Props/PropConfig.tsx, src/cloud/components/Props/PropSelectorModal.tsx, src/cloud/lib/hooks/props/index.ts, src/cloud/lib/props.ts, src/design/components/organisms/MetadataContainer/molecules/MetadataContainerRow.tsx
=> Docops v1/prop doc page UI

package-lock.json, package.json, src/cloud/api/status/index.ts, src/cloud/components/Modal/contents/SmartView/ConditionItem.tsx, src/cloud/components/Modal/contents/SmartView/ConditionValueControl.tsx, src/cloud/components/Modal/contents/SmartView/StatusSelect.tsx, src/cloud/components/Props/Pickers/StatusSelect.tsx, src/cloud/components/Props/PropPicker.tsx, src/cloud/components/Props/PropSelectorModal.tsx, src/cloud/interfaces/db/props.ts, src/cloud/interfaces/db/smartView.ts, src/cloud/interfaces/db/status.ts, src/cloud/lib/props.ts, src/cloud/lib/smartViews.ts, src/cloud/lib/stores/status/index.ts, src/design/components/atoms/Scroller.tsx, src/design/components/molecules/Form/atoms/FormColorSelect.tsx, src/design/components/organisms/MetadataContainer/molecules/MetadataContainerRow.tsx
=> Docops v1/status prop integration

src/cloud/components/DocPage/DocTagsList/TagsAutoCompleteInput.tsx, src/cloud/components/DocPage/DocTagsList/index.tsx, src/cloud/components/Props/Pickers/PropertyValueButton.tsx, src/cloud/components/Props/Pickers/StatusSelect.tsx, src/cloud/components/Views/Table/TableViewContentManager.tsx
=> no label on empty prop picker

src/cloud/components/Views/Table/TableViewContentManager.tsx, src/cloud/components/Views/Table/TableViewContentManagerFolderRow.tsx, src/cloud/components/Views/Table/TableViewContentManagerRow.tsx
=> folder list styling

src/cloud/components/ContentManager/SortingOption.tsx, src/cloud/components/Views/Table/TableViewContentManager.tsx
=> doc row ordering

src/cloud/components/Application.tsx, src/cloud/lib/shortcuts.ts
Remove team members shortcut
Issue: https://github.com/Boostnote/BoostHub/issues/1548
=> Remove team members shortcut

src/cloud/api/track/index.ts, src/cloud/components/DashboardPage/index.tsx, src/cloud/components/Props/PropPicker.tsx, src/cloud/interfaces/analytics/mixpanel.ts, src/cloud/lib/hooks/props/index.ts, src/cloud/lib/hooks/views/tableView.ts
=> Docops v1/analytics

src/cloud/components/DocPage/NewDocContextMenu.tsx, src/cloud/lib/i18n/enUS.ts, src/cloud/lib/i18n/types.ts
Fixes #1153
---
<details>
<summary>
</summary>
This pull request has been submitted to:
- [#1153: Show more status of a document](https://issuehunt.io/repos/74213528/issues/1153)
---
</details>
=> feat(DocContextMenu): show word/character count

src/cloud/components/Router.tsx
- Fixed inifite loading when opening page components without `getInitalProps` first time
=> Fix page prop fetching when getInitalProps method is undefined

src/cloud/components/ContentManager/ContentManagerToolbar.tsx, src/cloud/components/Props/Pickers/NumberSelect.tsx, src/cloud/components/Props/PropPicker.tsx, src/cloud/components/Props/PropsAddForm.tsx, src/cloud/lib/props.ts
- Add number prop
- Add input change for number prop
- Add default value and error message on not a number
Video showcase:
https://user-images.githubusercontent.com/18196945/144726024-4d0a1736-fece-4b64-a90d-dffb0ac4350b.mp4
Issue: 
https://boostnote.io/boostio/Number-property-dC595cea6a7bbf4b0e80678a086ccc0380
=> Add number prop type

src/cloud/lib/mappers/fuzzyNavigation.ts, src/design/components/organisms/FuzzyNavigation/index.tsx, src/design/components/organisms/FuzzyNavigation/molecules/FuzzyNavigationItem.tsx
Add recent doc content
Add loading of the doc if not yet fetched
Showcase:
https://user-images.githubusercontent.com/18196945/144765157-04191a71-ff8c-4d47-84cf-ed2081956e72.mp4
Issue: 
https://github.com/Boostnote/BoostHub/issues/1184
=> Add initial search preview rendering

src/cloud/components/Props/PropAddModal.tsx, src/cloud/components/Props/PropSelectorModal.tsx, src/cloud/components/Props/PropsAddForm.tsx, src/cloud/components/Views/Table/TableAddPropertyContext.tsx, src/design/components/molecules/SuggestionSelect.tsx
Refactor `PropAddForm` to be more re-usable
=> Docops v3 refactor prop select

src/cloud/components/Props/Pickers/NumberSelect.tsx, src/cloud/components/Props/Pickers/TextSelect.tsx, src/cloud/components/Props/PropPicker.tsx, src/cloud/lib/props.ts, src/design/components/organisms/FuzzyNavigation/index.tsx, src/design/components/organisms/FuzzyNavigation/molecules/FuzzyNavigationItem.tsx
- Fixed Text prop selector
- Fixed Number prop selector
- Fixed scrolling behavior and active item style of fuzzy search
=> Fix style issues

src/cloud/components/Editor/index.tsx, src/cloud/lib/editor/plugins/pasteFormatPlugin.ts
Fixes #537
For reference (Google Sheets)
https://user-images.githubusercontent.com/9989487/144561550-7fcdaadb-3620-42f4-bff9-cc8d97186afd.mp4
---
<details>
<summary>
</summary>
This pull request has been submitted to:
- [#537: Pasting of tables](https://issuehunt.io/repos/74213528/issues/537)
---
</details>
=> feat(Editor): automatically paste sheet as markdown table

src/cloud/lib/hooks/sidebar/useCloudDnd.ts
- Discarded unnecessary workspaceId validation
=> Discard wrong drop location validation

src/design/components/organisms/Topbar/index.tsx, src/design/components/organisms/Topbar/molecules/TopbarBreadcrumb.tsx
before:
- click => openNavTree
- Double click => navigate
- On right click => actions 
after: 
- click => navigate
- Double click / Right click => nav tree
=> breadcrumbs UX changes

src/cloud/components/Router.tsx, src/cloud/components/sources/GithubSourceCallbackPage.tsx
- Added `/sources/github/callback` route for redirection from Github after our Gtihub app installation
=> Add prototype github source callback page

src/cloud/components/DashboardPage/DashboardView.tsx, src/cloud/components/Views/List/index.tsx, src/cloud/components/Views/Table/TableView.tsx, src/cloud/components/Views/ViewsSelector/index.tsx, src/cloud/components/Views/index.tsx, src/cloud/interfaces/db/view.ts, src/cloud/lib/hooks/views/listView.ts, src/cloud/lib/hooks/views/tableView.ts, src/cloud/lib/hooks/views/viewHandler.ts
- Used shortId for navigating views.
=> Use shortId to navigate views

src/cloud/components/DocPage/index.tsx, src/cloud/components/Props/Pickers/DocDependencySelect.tsx, src/cloud/interfaces/db/props.ts, src/cloud/lib/hooks/useCloudDocPreview.tsx, src/cloud/lib/hooks/useCloudResourceModals.tsx, src/cloud/lib/stores/nav/store.tsx, src/cloud/lib/stores/nav/types.ts
- fix routing for doc preview modal in DependencyPropPicker
- fix initialMaps population to take into account dependencies prop's doc as well
=> Doc properties - Dependency & Doc Preview Modal routing

src/design/components/organisms/Kanban/hook.ts
Fix type errors caused by new `dnd-kit` version
=> fix custom collision detection for new dnd-kit version

src/cloud/api/teams/props/index.ts, src/cloud/components/Modal/contents/SmartView/ConditionItem.tsx, src/cloud/components/Modal/contents/SmartView/ConditionValueControl.tsx, src/cloud/components/Props/Pickers/CheckboxSelect.tsx, src/cloud/components/Props/PropPicker.tsx, src/cloud/components/Views/Kanban/Item.tsx, src/cloud/components/Views/Table/TableView.tsx, src/cloud/interfaces/db/props.ts, src/cloud/interfaces/db/smartView.ts, src/cloud/lib/props.ts, src/cloud/lib/smartViews.ts
Add checkbox prop type
Add checkbox select view
Showcase:
https://user-images.githubusercontent.com/18196945/152653176-6457b815-8980-498d-a4a2-4c029a4bc745.mp4
=> Add checkbox implementation

src/cloud/components/Views/Kanban/index.tsx, src/cloud/lib/hooks/useCloudResourceModals.tsx
Add doc button in header of Kanban lists
Showcase:
https://user-images.githubusercontent.com/18196945/152700557-c0a191bf-f450-4fe4-aeae-ab2c426e3773.mp4
=> Add new doc button for Kanban header

src/cloud/components/Views/Kanban/ListSettings.tsx, src/cloud/components/Views/Kanban/index.tsx, src/design/components/molecules/LabelManager.tsx
Refactor List Settings component
Reuse LabelManager
Showcase:
https://user-images.githubusercontent.com/18196945/152702479-0f0736c8-40e3-4f66-bdae-bc87351d7250.mp4
=> Add Kanban list status options

src/cloud/components/Automations/FilterBuilder.tsx
Reset filter input when adding a new filter
=> reset filter input value on filter creation

src/cloud/components/ContentManager/ContentManagerToolbar.tsx, src/cloud/components/Views/EditableDocItemContainer.tsx, src/cloud/interfaces/db/beta.ts, src/cloud/lib/hooks/sidebar/useCloudSidebarTree.tsx, src/cloud/lib/stores/beta/store.ts, src/design/components/atoms/EditableInput.tsx
=> Fix prettier errors

src/cloud/pages/workflows/create.tsx
- Added toast message when creating a workflow
=> Implement workflow creation toast

src/cloud/components/Comments/CommentInput.tsx, src/cloud/components/Comments/CommentList.tsx, src/cloud/components/Comments/CommentManager.tsx, src/cloud/components/Comments/ThreadItem.tsx, src/cloud/components/Comments/ThreadList.tsx
|Before|After|
|--|--|
|<img width="503" alt="Screen Shot 2022-02-08 at 2 07 58 AM" src="https://user-images.githubusercontent.com/8602615/152837006-1c9f444c-1194-4b01-90bc-3e7a3255e77b.png">|<img width="508" alt="Screen Shot 2022-02-08 at 2 07 06 AM" src="https://user-images.githubusercontent.com/8602615/152836996-5233dd2d-5432-4224-ae96-7a93311a2e53.png">|
=> Comment UI fixes

src/cloud/api/teams/docs/index.ts, src/cloud/components/DocPage/DocContextMenuActions.tsx, src/cloud/components/Views/EditableDocItemContainer.tsx, src/cloud/components/Views/Kanban/index.tsx, src/cloud/lib/hooks/useCloudApi.tsx, src/cloud/lib/i18n/enUS.ts, src/cloud/lib/i18n/fr.ts, src/cloud/lib/i18n/ja.ts, src/cloud/lib/i18n/types.ts, src/cloud/lib/i18n/zhCN.ts, src/cloud/lib/props.ts, src/design/lib/hooks/useBulkApi.ts
Add duplicate doc in the context menu
Add duplicate doc in the folder doc list doc context menu
Add props handling function
Showcase:
https://user-images.githubusercontent.com/18196945/152644254-9092e50a-63c9-4fe9-b041-462ae998bf7b.mp4
=> Add duplicate action

src/cloud/api/teams/docs/index.ts, src/cloud/components/Automations/actions/PropertySelect.tsx, src/cloud/components/DocPage/DocContextMenuActions.tsx, src/cloud/components/Views/EditableDocItemContainer.tsx, src/cloud/components/Views/Kanban/ListSettings.tsx, src/cloud/components/Views/Kanban/index.tsx, src/cloud/lib/hooks/useCloudApi.tsx, src/cloud/lib/hooks/useCloudResourceModals.tsx, src/cloud/lib/i18n/enUS.ts, src/cloud/lib/i18n/fr.ts, src/cloud/lib/i18n/ja.ts, src/cloud/lib/i18n/types.ts, src/cloud/lib/i18n/zhCN.ts, src/cloud/lib/props.ts, src/design/components/atoms/EditableInput.tsx, src/design/components/molecules/LabelManager.tsx, src/design/lib/hooks/useBulkApi.ts
- Add new doc button for Kanban header
- add duplicate doc actions
- fix obsolete json type
- fix spacebar input keydown in kanban view
- fix new doc button style and dashboard bug
=> Add new doc button for Kanban header (#1482)

src/cloud/components/Comments/CommentInput.tsx, src/cloud/components/Comments/ThreadItem.tsx
Change to created date of the first comment instead of last comment date
Test: Old one shows latest comment date, fixed shows initial comment data
=> Comment Date For Thread

src/cloud/components/DocPage/DocContextMenuActions.tsx, src/cloud/components/DocPreview/DocPreviewRealtime.tsx, src/cloud/components/DocPreview/index.tsx, src/cloud/components/FolderPage/index.tsx, src/cloud/components/ViewerDisclaimer.tsx, src/cloud/components/Views/Calendar/CalendarNoDateContext.tsx, src/cloud/components/Views/Calendar/CalendarView.tsx, src/cloud/components/Views/Calendar/CalendarWatchedPropContext.tsx, src/cloud/components/Views/EditableDocItemContainer.tsx, src/cloud/components/Views/Kanban/index.tsx, src/cloud/components/Views/List/ListViewItem.tsx, src/cloud/components/Views/Table/TableView.tsx, src/cloud/components/Views/ViewsSelector/index.tsx, src/cloud/components/Views/index.tsx, src/cloud/components/WorkspacePage/index.tsx, src/cloud/lib/hooks/useCloudApi.tsx, src/cloud/lib/i18n/enUS.ts, src/cloud/lib/i18n/fr.ts, src/cloud/lib/i18n/ja.ts, src/cloud/lib/i18n/types.ts, src/cloud/lib/i18n/zhCN.ts, src/design/components/organisms/Table/molecules/TableRow.tsx, src/design/components/organisms/Toast.tsx, src/design/lib/stores/toast/index.ts
- do not allow viewers to edit the doc in doc preview
- fix checkboxes UI in table design component
- fix toast body parsing issue in create doc api
- remove the error status in prod environment
- prevent viewers to edit props, views.
=> Viewer UI fixes

src/cloud/components/DocPreview/DocPreviewRealtime.tsx, src/cloud/components/Editor/index.tsx, src/cloud/components/Topbar/SyncStatus.tsx, src/design/components/atoms/Spinner.tsx
Add popup
Test:
- Stop real-time events 
- Run real-time events
- Try to reconnect
Showcase (UI and test):
https://user-images.githubusercontent.com/18196945/153708188-c26f7205-43cb-44ca-8045-7f5e347e6edf.mp4
=> Refactor connect and reconnect

src/cloud/components/DocProperties.tsx, src/cloud/components/Props/Pickers/StatusSelect.tsx, src/cloud/components/Views/Calendar/CalendarView.tsx, src/cloud/components/Views/Calendar/CalendarViewPropertiesContext.tsx, src/cloud/components/Views/Calendar/CalendarWatchedPropContext.tsx, src/cloud/components/Views/Kanban/KanbanViewPropertiesContext.tsx, src/cloud/components/Views/Kanban/index.tsx, src/cloud/components/Views/List/ListViewPropertiesContext.tsx, src/cloud/components/Views/List/index.tsx, src/cloud/components/Views/Table/TableView.tsx, src/cloud/components/Views/Table/TableViewPropertiesContext.tsx, src/cloud/lib/hooks/sidebar/useCloudSidebarTree.tsx, src/design/components/molecules/LabelManager.tsx, src/design/lib/stores/toast/index.ts
- fix production api error message
- fix padding viewer table view
- hide `add property` button for viewers in doc properties
- allow viewers to add dashboards/smartviews and edit its views
=> Viewers dashboards

src/cloud/components/Modal/contents/SmartView/ConditionItem.tsx, src/cloud/components/Modal/contents/SmartView/ConditionValueControl.tsx, src/cloud/components/Modal/contents/SmartView/FolderSelect.tsx, src/cloud/interfaces/db/smartView.ts, src/cloud/lib/i18n/enUS.ts, src/cloud/lib/i18n/fr.ts, src/cloud/lib/i18n/ja.ts, src/cloud/lib/i18n/types.ts, src/cloud/lib/i18n/zhCN.ts, src/cloud/lib/smartViews.ts, src/design/components/molecules/Form/atoms/FormSelect.tsx
Add folder filter in UI
Add workspace explorer for folder value select
Showcase:
General adding of filters and conditions
https://user-images.githubusercontent.com/18196945/155721536-9fc33d69-958f-4bd7-9ace-d2dbaaec514c.mp4
Filter removal:
https://user-images.githubusercontent.com/18196945/155721547-2bf14f22-33cd-4665-83d1-921ceb659810.mp4
=> Add folder filter for smart views

src/cloud/components/Comments/ThreadItem.tsx
=> Fix reply count

src/cloud/components/Comments/ThreadList.tsx
=> Update thread list order

src/cloud/components/Comments/CommentList.tsx, src/cloud/components/Comments/CommentManager.tsx, src/cloud/components/Views/EditableDocItemContainer.tsx, src/cloud/lib/i18n/enUS.ts, src/cloud/lib/i18n/fr.ts, src/cloud/lib/i18n/ja.ts, src/cloud/lib/i18n/types.ts, src/cloud/lib/i18n/zhCN.ts
Add prompt for comment and thread deletion
Add prompt for doc deletion in folder views
Showcase:
https://user-images.githubusercontent.com/18196945/155331375-99048234-d9a4-4238-8fd3-a08ec09da173.mp4
=> Add prompts for deletion of items

src/cloud/components/Views/EditableDocItemContainer.tsx
Fix background color of the context menu
Showcase:
=> Update context menu background in Kanban

src/cloud/components/Editor/EditorToolbar.tsx, src/cloud/components/Editor/types.ts, src/cloud/lib/i18n/enUS.ts, src/cloud/lib/i18n/fr.ts, src/cloud/lib/i18n/ja.ts, src/cloud/lib/i18n/types.ts, src/cloud/lib/i18n/zhCN.ts
Add math option
Add brackets
Showcase same as in local space:
https://user-images.githubusercontent.com/18196945/159178865-18979a80-77ba-4e64-bd20-9eef90100f13.mp4
=> Add editor toolbar improvements

src/cloud/components/Editor/index.tsx, src/cloud/lib/editor/CodeMirror.ts
Add some configuration and suggestions for CodeMirror autocomplete
Implement autocomplete show and hide and completion callbacks
WARN: 'Ceylon' mode does not seem to work for 'ceylon' mime type, the actual type should be 'text/x-ceylon', but that works only in the editor, in preview it does not work well.
Showcase:
https://user-images.githubusercontent.com/18196945/161429560-ac0c30e4-ec90-4698-871e-4854314862dd.mp4
=> Add show hint addon

src/electron/menu.ts
Change URL for add space in new window
Todo:
- Not tested in production
=> Fix add space menu URL link

src/cloud/components/Props/Pickers/UrlSelect.tsx
https://user-images.githubusercontent.com/18196945/166823762-40590c49-77f4-4bbb-8a91-61b6253451a0.mp4
=> Add url open in kanban view

src/cloud/components/DocPage/SharedDocPage.tsx, src/cloud/components/Editor/index.tsx, src/cloud/components/MarkdownView/CustomizedMarkdownPreviewer.tsx, src/cloud/components/MarkdownView/index.tsx, src/cloud/lib/charts/flowchart.tsx, src/mobile/components/pages/DocViewPage.tsx
Add warning for opening attachment link
https://user-images.githubusercontent.com/18196945/168489261-636d2530-88b1-4b57-851f-1e4f3a555ef3.mp4
Add flowchart rendering warning block:
=> Add safe link open warning

src/cloud/components/Comments/ThreadItem.tsx, src/cloud/components/DocPage/index.tsx, src/cloud/components/Editor/index.tsx, src/cloud/components/Modal/contents/DiscountModal.tsx, src/cloud/components/Modal/contents/Workspace/WorkspaceModalForm.tsx, src/cloud/components/Subscription/SidebarSubscriptionCTA.tsx, src/cloud/components/Subscription/SubscriptionManagement.tsx, src/cloud/components/Subscription/SubscriptionPlanTables.tsx, src/cloud/components/SubscriptionForm/index.tsx, src/cloud/components/ViewerDisclaimer.tsx, src/cloud/components/settings/SubscriptionTab.tsx, src/cloud/components/settings/TeamSubLimit.tsx, src/cloud/components/settings/UpgradeTab.tsx, src/cloud/lib/i18n/enUS.ts, src/cloud/lib/i18n/fr.ts, src/cloud/lib/i18n/ja.ts, src/cloud/lib/i18n/zhCN.ts, src/cloud/lib/stores/pageStore/store.tsx, src/cloud/lib/stores/pageStore/types.ts, src/cloud/lib/subscription.ts, src/mobile/components/organisms/modals/SpaceBillingsTab.tsx, webpack.cloud.config.ts
- Display trial length and remaining time.
- Remove Free Plan from plan info table
=> Display trial length
