BoostIO/BoostNote-App

src/lib/db/store.spec.ts
src/lib/db/store.ts
webpack.config.ts

##Fix [notion](https://www.notion.so/boostio/2069b7057f4b436bac3ad5300a85eb27?v=c6a532520ca84175989b7828cd8b536c&p=4508aa48f23b492baba8994c018cdbd9)
- corrected initialize of dotenv
- modified `createNote`, `updateNote` functions
- added tests for each function
https://gyazo.com/0897fe6dcec9926302175d7f7dd46a84

Update tags store on create / update note

---

src/lib/db/NoteDb.ts
src/lib/db/store.spec.ts
src/lib/db/store.ts

- Untrash note db upsert for tags
- Update `tagMap`, `foldermap`, `noteMap` on`untrashNote` hook.
However: 
- We do not really delete tags for now, so the tag `upsert` may be unnecessary
- We do not currently modify `tagMap` on the `trashNote` hook ( handled by the filter on trashed state of the note ), so the tagMap modification may be unnecessary.
Also, trashed notes are still accessible by their `app/storages/{storage}/tags/{tag}/{noteId}` scheme, is it intended or not?

Untrash Note

---

src/lib/db/store.spec.ts
src/lib/db/store.ts

- Trashes notes and child folders' notes and update `noteMap`
- remove trashed `noteIds` from `tagMap`

remove folder hook and tests update

---

src/components/Router.tsx
src/components/Storage/CloudStorageSelector.tsx
src/components/Storage/StorageCreate.tsx
src/components/Storage/StorageEdit.tsx
src/components/Storage/index.ts
src/lib/accounts/users.ts
src/lib/db/store.ts
src/lib/db/types.ts
src/lib/router/utils.ts
src/lib/utils/predicates.ts

Implement edit storage page
- Ability to link and unlink storage
- Extracted cloud storage selection into separate component shared across `StorageCreate` and `StorageEdit` componenets.
- Add `name` information for linked cloud storage on local storage information
- required implementing an `optional` predicate
- Local storage name saves using a debounce
- Cloud storage name now always shows on create but defaults to local storage
- Cloud user info is cached

implement edit storage page

---

src/components/NotePage/NoteList/NoteItem.tsx

NoteItem preview style fix

---

src/components/NotePage/NoteList/NoteList.tsx
src/components/NotePage/NotePage.tsx

Styled NoteList and Note Detail when there is no note

---

src/components/SideNavigator/ControlButton.tsx
src/components/SideNavigator/SideNavigator.tsx
src/components/SideNavigator/SideNavigatorItem.tsx

Styled the SideNavigator

---

src/components/NotePage/NoteList/NoteItem.tsx

Styled the NoteList

---

src/components/NotePage/NoteDetail/NoteDetail.tsx
src/components/NotePage/NotePage.tsx

[Sepia theme](https://gyazo.com/ca4d3ee25395d0355226a9530a46aa78)

ariane thread for notes

---

src/components/Modal/contents/DownloadOurAppModal.tsx
src/components/Modal/contents/styled.ts
src/components/PreferencesModal/AboutTab.tsx
src/components/atoms/AppLink.tsx

fix app link in about page

---

src/components/NotePage/NoteList/NoteList.tsx
src/lib/styled/styleFunctions.ts

Styled select tab

---

src/components/NotePage/NoteList/NoteList.tsx
src/components/NotePage/NotePage.tsx
src/components/SideNavigator/FolderListFragment.tsx
src/components/SideNavigator/SideNavigator.tsx
src/lib/db/NoteDb.spec.ts
src/lib/db/NoteDb.ts
src/lib/db/store.spec.ts
src/lib/db/store.ts
src/lib/db/utils.spec.ts
src/lib/db/utils.ts

- Users can see all notes among all folders from Storage name nav
- Delete the current root folder (All Notes) Root folder no longer exists, cannot be created.
- Create a default folder called "Default" automatically when storage is created
- Migrate notes in "All Notes" to "Default"
- Hide new note button other than UI that users choose the folder
- New note on right-click on the folder
- Users can not create note if there is no folder
- Fixed bug where synced notes would not update their storageId

Restructure root folder

---

src/components/Tutorials/TutorialsNoteDetail.tsx
src/components/Tutorials/TutorialsPage.tsx

When clicking `tutorials`, I got errors.
I tried to change `TutorialsNoteDetail.tsx ` to function component, but it was a big deal than this, and it isn't a case that I can decide, I think.
So I fixed like this.

Fixed error caused by using hooks inside of class component

---

src/components/CodeMirrorStyle.tsx
src/components/atoms/CodeEditor.tsx
src/components/atoms/MarkdownPreviewer.tsx
src/lib/CodeMirror.ts

This is not 100% finished as I have run into an issue.
I have added the line to add solarized dark to the editor themes. This applies fine but not so when i add it to the code blocks. See image.
I am happy to continue the work but would appreciate a pointer to help find out what is up.

Add  solarized dark to editor themes

---

src/components/NotePage/NotePage.tsx

issue: https://github.com/BoostIO/BoostNote.next/issues/278
Change to edit mode when you tap createNote button in view only mode

Change to edit mode when tap createNote button

---

src/components/NotePage/NoteList/NoteItem.tsx
src/lib/i18n/enUS.ts
src/lib/i18n/esEs.ts
src/lib/i18n/ja.ts
src/lib/i18n/ko.ts
src/lib/i18n/ptBR.ts
src/lib/i18n/zhCN.ts

Regardless of whether it has been deleted, the following menu is displayed when select note item.
```
- Duplicate
- Delete
- Bookmark | Remove bookmark
```
But I think `Duplicate` and `Bookmark | Remove bookmark` menu should not be shown when select trashed note.
When select trashed note, the following menu is desirable
```
- Delete
- Restore
```
`Restore` behaves the same as tapping untrashed icon
- Add `note.restore`( some language I didn't understand remains `Restore`)
- Show restore and delete menu when `note.trashed` is true(not show duplicate and bookmark menu)

【Suggestion】Show restore menu when select trashed note

---

src/lib/i18n/de.ts

Add german translation

---

CONTRIBUTING.md
src/lib/preview.ts

this Pullrequest changes styling for `code` elements.

Code styling

---

src/locales/de.ts

General overhaul of the de-localization.
I feel like ```Speicherort``` as the main translation for ```storage``` is generally correct but quite unusual. You should think about maybe changing it to something like ```Notizbuch = Notebook``` on many occasions. If you wish to implement that feel free to ask me to translate it.
'note.date': currently it says e.g. ```38 minutes her``` but it should either be ```38 Minuten her``` or ```vor 38 Minuten```. IMO the second one is better, but I think more code adjustment is necessary somewhere else to rephrase the wording.
Btw: where can I translate other things like e.g. ```Storage Settings``` or ```Remove Storage``` when you edit your storage?

General overhaul of the de-localization

---

package.json

**Requires rpm build essentials**
- Addresses Issue #441 
The project's `electron-builder` build script are based on the current architecture/OS of the user, so it probably needs redhat-based machines (ex. Fedora, CentOS, etc.) to achieve `.rpm` builds.
-----
I also **suggest** seperating `electron-builder` configurations to its own dedicated file: `electron-builder.yml` to avoid the cluttering of `package.json`.
> `json`, `json5`, `toml` or `js` (exported configuration or function that produces configuration) formats also supported.

RPM build target | #441

---

src/electron/index.ts

Limits electron app windows size enough to see the panes.
> Remake of #459 after accidental rebase & push on wrong branch.

Limit electron app window size

---

src/lib/preview.ts

Removes all duplicate CSS in Preferences > Markdown > Preview Style
This shouldn't change the look from any existing styling, just deletes and refactors.  Combined some attributes into the same spot so they aren't in multiple places.
[Issue 435](https://github.com/BoostIO/BoostNote.next/issues/435)
Tested changes on electron and web app (Firefox) on OpenSuse Leap 15.1
If anything was missed please let me know!

Remove duplicated CSS from preview style section | #435

---

src/components/atoms/MarkdownPreviewer.tsx

The table align bug has been reported here: https://github.com/BoostIO/BoostNote.next/issues/513
This PR allow `align` to appears in HTML

Fixed the table align

---

src/components/PreferencesModal/AboutTab.tsx

This new link matches the one used on the homepage.

Update Slack invite link

---

src/components/App.tsx
src/components/atoms/MarkdownPreviewer.tsx
src/lib/keyboard.ts

This PR fixed the unwanted select all when the markdown previewer is in focus.
Fixed: https://github.com/BoostIO/BoostNote.next/issues/531
This also allow global key listener to be run on all platform. if there's a reason why this is a bad thing to do, please tell me.

fixed ctrl + a on markdown previewer

---

src/components/GlobalStyle.tsx
src/components/PreferencesModal/PreferencesModal.tsx
src/components/PreferencesModal/TabButton.tsx

This PR improve the preference modal UI by limiting the width. This way the extra empty space will not looks awkward anymore
**Before:**
**After**

Improved preference modal UI

---

src/components/PreferencesModal/GeneralTab.tsx
src/components/pages/NotePage.tsx
src/lib/preferences.ts

I don't know if the wording on the front end of it describes very well what the option does. I didn't want to make it too long. Criticism is very welcome.
Fixes #419

Add option to show/hide contents of subfolders

---

src/components/atoms/TagNavigatorListItem.tsx
src/components/atoms/TagNavigatorNewTagPopup.tsx
src/components/atoms/TopbarSwitchSelector.tsx
src/lib/styled/BaseTheme.ts
src/lib/styled/styleFunctions.ts
src/themes/dark.ts
src/themes/legacy.ts
src/themes/light.ts
src/themes/sepia.ts
src/themes/solarizedDark.ts

- Some colors in the topbar & buttons were broken, so I fixed them
- There were no styles for the tag input, so I added some styles
- I removed hover & active state from the tag list item for now (this one causing some color issues in some of the themes)

UI: Adjusted Colors

---

src/components/PreferencesModal/MarkdownTab.tsx
src/components/PreferencesModal/PreferencesModal.tsx
src/components/PreferencesModal/styled.tsx

- Made the sidebar border to full length
- Adjusted font sizes of the selector & input
- Added some padding to the markdown previewed
| ![CleanShot 2020-10-26 at 17 52 20](https://user-images.githubusercontent.com/2410692/97154257-0711e780-17b7-11eb-9098-10b8378fb673.png)| ![image](https://user-images.githubusercontent.com/2410692/97154354-1db83e80-17b7-11eb-8d40-824ced26abba.png) |
| ![CleanShot 2020-10-26 at 18 05 05](https://user-images.githubusercontent.com/2410692/97154413-2f99e180-17b7-11eb-96b0-9a14f7341a39.png) | ![CleanShot 2020-10-26 at 18 03 32](https://user-images.githubusercontent.com/2410692/97154429-34f72c00-17b7-11eb-881b-d513732a0d56.png) |
| ![CleanShot 2020-10-26 at 18 09 …

UI: Adjusted Preferences Modal Styles

---

src/components/organisms/FolderDetail.tsx

There were no styles for the sort (selector), so I applied the default selector style and made it a bit bigger.
| ![CleanShot 2020-10-26 at 18 27 16](https://user-images.githubusercontent.com/2410692/97155935-5d802580-17b9-11eb-8c14-1452bcffa7a2.png) | ![CleanShot 2020-10-26 at 18 28 35](https://user-images.githubusercontent.com/2410692/97155963-683aba80-17b9-11eb-83fe-f221ff2ea51d.png) |

UI: Adjusted Sort Style

---

src/components/molecules/FolderDetailListItem.tsx
src/lib/styled/BaseTheme.ts
src/themes/dark.ts
src/themes/legacy.ts
src/themes/light.ts
src/themes/sepia.ts
src/themes/solarizedDark.ts

- Legacy theme and Solarized Dark theme had weird hover style on the doc list, so I fixed the colors
- While doing that, I also had to fix the nav background colors of the side nav (only solarized dark)

UI: Fixed Doc List Hover Styles

---

src/components/organisms/NoteStorageNavigator.tsx

- Assigned the right colors to the text
- Made the height bigger and removed unnecessary margin

UI: Adjusted Styling of the Storage Switcher

---

src/components/molecules/AppNavigatorStorageItem.tsx
src/components/organisms/AppNavigator.tsx
src/lib/styled/BaseTheme.ts
src/themes/dark.ts
src/themes/legacy.ts
src/themes/light.ts
src/themes/sepia.ts
src/themes/solarizedDark.ts

I restyled the app navigators.
GIF doesn't look good, but you can check the actual color from the image instead ;)

UI: Restyled App Navigators

---

src/components/PreferencesModal/BillingTab.tsx

**Add checkmarks instead of circles in billing page** (commit-sha)
Update billing page basic and premium to have checkmarks arrows instead of empty circles
The billing page was:
Now is:
**Test:** 
In electron Linux App (dev)
In electron Linux App production version (appImage)

Add checkmarks instead of circles in billing page (#388)

---

homepage/components/organisms/Header.tsx
homepage/components/organisms/HeroSection.tsx
homepage/components/organisms/SubscribeNewsLettersForm.tsx
homepage/lib/i18n.ts
homepage/locales/de.ts
homepage/locales/en.ts
homepage/locales/es.ts
homepage/locales/fr.ts
homepage/locales/ja.ts
homepage/locales/ko.ts
homepage/locales/nl.ts
homepage/locales/pt.ts
homepage/locales/ptBR.ts
homepage/locales/ru.ts
homepage/locales/vn.ts
homepage/locales/zh.ts

I'm seding this pr to help with the issue #462.
I also extracted some hardcoded text to the translation files.

Homepage brazilian portuguese translation

---

homepage/components/organisms/Header.tsx
homepage/lib/i18n.ts
homepage/locales/hr.ts

Add homepage translation for Croatian language.
Original Translation: https://github.com/BoostIO/BoostNote.next/blob/master/homepage/locales/en.ts

Add homepage translation for Croatian (#462)

---

homepage/locales/en.ts
homepage/locales/fr.ts
homepage/locales/hr.ts
homepage/locales/ja.ts
homepage/locales/ko.ts
homepage/locales/nl.ts
homepage/locales/pt.ts
homepage/locales/ptBR.ts
homepage/locales/ru.ts
homepage/locales/vn.ts
homepage/locales/zh.ts

Typo fixes for Homepage.
For spanisch (#677) and german (#692) are separate PR available

Homepage Typo fix

---

homepage/locales/de.ts

Homepage German translation #462

Homepage Translation to German (#462)

---

src/components/organisms/ImportLegacyNotesForm.tsx
src/lib/db/FSNoteDb.ts
src/lib/db/createStore.ts
src/lib/db/types.ts

Fixes #631.
Currently we do not read `createdAt` or `updatedAt` props when importing notes from legacy.
Added `noteDocImportableProps` type, since adding `createdAt` and `updatedAt` props to `noteDocEditibleProps` doesn't sound right.
Changed `createNote` functions to accept either imported props or editable partial props.
Tested the following cases after importing notes from legacy:
- Confirmed the creation date and last update date are preserved.
- Confirmed that last update date is changed when I edit the note and save.
- Confirmed that I can create notes manually, and creation date and last update date are set to now.

Preserve Note Creation and Last Updated Times when Importing from Legacy (#631)

---

src/components/organisms/ImportLegacyNotesForm.tsx

Fixes #667.
`setState()` call in React runs asynchronously, making the `setStorageMap()` call inside `createFolder()` and `createNote()` asynchronous. React will batch these updates together, making value of `storageMap` is unreliable inside `createNote()`, which depends on the updates from `createFolder()` when importing legacy notes.
Calling `initialize()` will restore the `storageMap()` by repopulating `folderMap` and `noteMap`.

Initialize StorageMap after importing from legacy (#667)

---

src/components/atoms/MarkdownPreviewer.tsx

Fixed #698.
Currently, we display invisible text when the language specified for the code block is not recognized.
This is because in `MarkdownPreviewer.tsx: rehypeCodeMirrorAttacher()`, there is an edge case where if language is not null but there is no mime found for this language that can be found in `CodeMirror.findModeByName`, we set `node.children` to `[]`. 
Fix this case by returning early before the `node.children = cmResult` assignment.
Tested with following languages after applying the change above:
java -> rendered with java highlighting
123f (made up language) -> rendered as plain text
(empty) -> rendered as plain text

Show Plain Text in Preview for Unrecognized Languages (#698)

---

src/components/organisms/AttachmentList.tsx

#714 Reuse the attachment in another page. It also can search which pages use this image by copy the attachment name and paste it to the search box.

Copy the attachment name in attachment page (#714)

---

src/components/organisms/NotePageToolbar.tsx
src/lib/download.ts
src/lib/exports.ts

Add attachment rendering in PDF and HTML
- Add attachment getter in PDF export (exports.ts)
- Add parsing note md content to replace `<img src='id'>` with valid note image id
- id blob is replaced with object url link in PDF export
- id blob is replaced with base64 encoding of the image
- Update downloadBlob to have cleanup callback (for revoking objectURLs in PDF export)
How it works:
Users can export the PDF and HTML and any image link attached to document which renders well in markdown preview should be exported inside downloaded PDF and HTML (see more details in commit description).
How it looks:
**- md:** 
- [ImageGlobalSearchPDFExport.txt](https://github.com/BoostIO/BoostNote.next/files/5681100/ImageGlobalSearchPDFExport.txt)
- …

Add attachment rendering in PDF and HTML

---

src/components/PreferencesModal/styled.tsx
src/components/molecules/SearchModalNoteResultItem.tsx
src/components/organisms/NoteDetail.tsx
src/components/organisms/NoteStorageNavigator.tsx
src/components/organisms/SearchModal.tsx
src/components/pages/NotePage.tsx
src/components/pages/WikiNotePage.tsx
src/lib/colors.ts
src/lib/keyboard.ts
src/lib/search/search.ts
src/lib/storageRouter.ts
src/lib/string.ts
src/lib/styled/BaseTheme.ts
src/lib/styled/styleFunctions.ts
src/themes/dark.ts
src/themes/legacy.ts
src/themes/light.ts
src/themes/sepia.ts
src/themes/solarizedDark.ts

Add tag colors setup (#219, #629, #681, #570):
- Add search functionality and result data structures
- Add preview of found items, highlighted style, the rows of found items
- Add note preview
- Add selection of items in search
- Add text highlight in editor preview
- Add editor preview focus
- Add editor preview while clicking on found item
- Add better ID management and state update fix
- Add some stability updates (max searched content, max result line length)
- Add double click on search item to lead to focused item in editor
- Add focusLine number for editor to route params
- Add better colors across themes for search
General functionality:
Currently searches throught the content only (with some restrictions).
Setup for title/tags is commented out and can be added (title/tags …

Add initial global search setup

---

src/components/atoms/MarkdownPreviewer.tsx

Fixes #696
Boost Note currently seems to ignore all HTML tags (#737).
This PR allows `remarkRehype` to parse HTML tags as intended in #561, reflecting the changes in syntax-tree/mdast-util-to-hast#38. 
In addition, this PR will also allow attributes passed in `<img>` tags to be passed into the `AttachmentImage` component, allowing users to resize their images using this tag (#696).

Fix HTML Tags Not Being Rendered (#737)

---

src/components/atoms/MarkdownPreviewer.tsx
src/components/atoms/markdown/CodeFence.tsx

**Fix copy snippet without language** (#749)
- Reorder markdown preview attacher to set raw data even on null lang items
- Fix some style code issues and formatting in copy snipppet and save snippet as file
Test:
- In electron Linux App (dev)
- In electron Linux App production version (appImage)

Fix copy snippet without language

---

src/lib/db/FSNoteDb.ts
src/lib/string.ts

**Fix bug for renaming folders in file system database** (#747)
- Add escape for "[" character in regex escape characters
- Update FSNoteDb to use the regex escapes while renaming folder
Todo:
Test
- In electron Linux App (dev)
- In electron Linux App production version (appImage)

Fix bug for renaming folders in file system database

---

src/components/organisms/NotePageToolbar.tsx
src/lib/exports.ts

**Fix attachment urls being revoked too early** (#745 )
Fix ```parse.path``` to be able to test new PDF export
Update attachment logic to filter out duplicates
Fix attachment URLs being revoked too early
Test
- In electron Linux App (dev)
- In electron Linux App production version (appImage)

Fix attachment urls being revoked too early

---

package-lock.json
package.json
src/components/atoms/TagNavigatorListItem.tsx
src/components/atoms/TagNavigatorNewTagPopup.tsx
src/components/atoms/dialog/DialogColorPicker.tsx
src/components/atoms/dialog/styled.ts
src/components/molecules/FolderNavigatorItem.tsx
src/components/molecules/NoteDetailTagNavigator.tsx
src/components/molecules/NoteItem.tsx
src/components/molecules/StorageNavigatorFragment.tsx
src/components/molecules/TagListFragment.tsx
src/components/organisms/NoteListNavigator.tsx
src/components/organisms/NotePageToolbar.tsx
src/components/organisms/NoteStorageNavigator.tsx
src/components/organisms/SearchModal.tsx
src/components/pages/NotePage.tsx
src/lib/colors.ts
src/lib/db/FSNoteDb.ts
src/lib/db/PouchNoteDb.ts
src/lib/db/createStore.ts
src/lib/styled/styleFunctions.ts

Add tag colors setup (#323):
- Add tag context menu (right click on tag) for chosing colors
- Add react color as color pickers library
- Add basic DB management for tags with color (FSNote, PouchDB, createStore API)
- Add basic UI component (react-color) for choosing the color
- Add basic handling of color brightness in tags and hover styles (black/white inversion, brigther, dimmer when bg is dark/light)
- Add colored tags inside note list note tag list
Fix right click context menu in sidebar
How it works:
Users can right click on any tag in note tag list. The color picker comes up and on selection it changes colors (preview is below in color slider at right corner), below that are some predefined colors which can be clicked. Once user is satisfied with color, to close the dialog any …

Add tag colors setup

---

src/components/atoms/ToolbarIconButton.tsx
src/components/organisms/NotePageToolbar.tsx

I restyled the view mode switcher of the doc page to make it look the same as the team version.
(https://github.com/BoostIO/BoostNote.next/pull/758 needs to be merged before this to apply the correct text color.)
| <img width="208" alt="Screen_Shot_2021-01-07_at_16 09 35" src="https://user-images.githubusercontent.com/2410692/103988350-4dc98800-51d1-11eb-888f-7f9e43bcc31f.png"> | <img width="197" alt="CleanShot 2021-01-08 at 16 42 26@2x" src="https://user-images.githubusercontent.com/2410692/103988371-5cb03a80-51d1-11eb-831e-c0bf05cbb8b8.png"> |

UI: Changed Switcher Style

---

src/cloud/components/atoms/EditableInput.tsx

I adjusted the font size and made it the same with other breadcrumbs.
| <img width="400" alt="Screen_Shot_2021-02-17_at_12 07 40" src="https://user-images.githubusercontent.com/2410692/108465360-32b86080-72c5-11eb-89a1-0c558834b5b9.png"> | ![CleanShot 2021-02-19 at 15 11 25](https://user-images.githubusercontent.com/2410692/108465389-406de600-72c5-11eb-85c8-a817173a39f8.png) |

UI: Adjusted Font Size of Document Title

---

src/cloud/components/organisms/settings/UpgradeTab.tsx

I restyled the upgrade tab on the settings modal to make it look nicer.
| <img width="855" alt="Screen_Shot_2021-02-17_at_16 16 41" src="https://user-images.githubusercontent.com/2410692/108491767-aec3a000-72e7-11eb-8ae0-98e2a76b0e86.png"> | ![dark](https://user-images.githubusercontent.com/2410692/108493120-4ecdf900-72e9-11eb-99d5-a0a34b2803a0.png) ![light](https://user-images.githubusercontent.com/2410692/108493125-51305300-72e9-11eb-8b41-6b0e335b9ef3.png) |

UI: Restyle Upgrade Tab

---

src/components/organisms/NoteContextView.tsx
src/themes/dark.ts

I adjusted some styles of the doc context menu on the local app to make it look close enough with the cloud one.
| ![CleanShot 2021-02-20 at 15 15 08](https://user-images.githubusercontent.com/2410692/108585938-b25e3200-738e-11eb-9678-53434c1dbb09.png) | ![CleanShot 2021-02-20 at 14 50 49@2x](https://user-images.githubusercontent.com/2410692/108585944-bb4f0380-738e-11eb-92c8-a16661305e2b.png) |

UI: Adjusted Styles of Context Menu

---

src/cloud/components/organisms/Modal/contents/Import/styled.ts

I adjusted the styles of the import modal.
- Adjusted spacing
- Adjusted font sizes
| ![CleanShot 2021-02-20 at 15 33 23](https://user-images.githubusercontent.com/2410692/108586632-23074d80-7393-11eb-9fb4-a1a6afa75505.png) | ![CleanShot 2021-02-20 at 15 44 18](https://user-images.githubusercontent.com/2410692/108586646-34e8f080-7393-11eb-9262-3cce93a1dd06.png) |

UI: Adjusted Import Modal Styles

---

src/cloud/components/organisms/DocPage/View.tsx

Currently, the context menu covers the content of the archived page, so I fixed it to show the whole content.
| <img width="884" alt="Screen_Shot_2021-02-10_at_11 09 54" src="https://user-images.githubusercontent.com/2410692/108663627-5a513800-7514-11eb-8f07-1caa2da05552.png"> | ![CleanShot 2021-02-22 at 13 40 00](https://user-images.githubusercontent.com/2410692/108663661-6806bd80-7514-11eb-902b-d247ee007d3a.png) |

UI: Fix Content Width of the Archived Page

---

src/cloud/api/rest/doc.ts
src/cloud/api/teams/files/index.ts
src/cloud/api/teams/workspaces/index.ts
src/components/PreferencesModal/MigrationTab.tsx
src/components/PreferencesModal/PreferencesModal.tsx
src/components/PreferencesModal/StorageTab.tsx
src/components/atoms/ProgressBar.tsx
src/components/molecules/CloudWorkspaceSelect.tsx
src/lib/migrate.ts

Cloud migration

---

src/components/atoms/MarkdownPreviewer.tsx

…d ext when they are undefined.
When code block is set in `dockerfile` language mode, properties `mimes` and `ext` are undefined so I add optional chaining when accessing their element.

fix(markdown-code-block-lang-mode): Fix accessing element of mimes and ext when they are undefined.

---

src/cloud/components/organisms/Sidebar/SidebarTeamPickerContext.tsx

I made the member length hidden for guests.
| <img width="295" alt="Screen_Shot_2021-02-17_at_11 56 44" src="https://user-images.githubusercontent.com/2410692/110075307-f22d0c80-7dc5-11eb-8bed-5cbb0b8b0b8a.png"> | ![image](https://user-images.githubusercontent.com/2410692/110075429-230d4180-7dc6-11eb-925f-a3322ea4a1c6.png) |

UI: Hide Member Length for Guests

---

src/cloud/components/organisms/settings/ApiTab.tsx
src/cloud/components/organisms/settings/AppFeedbackTab.tsx
src/cloud/components/organisms/settings/InfoTab.tsx
src/cloud/components/organisms/settings/IntegrationsTab.tsx
src/cloud/components/organisms/settings/MembersTab.tsx
src/cloud/components/organisms/settings/PersonalInfoTab.tsx
src/cloud/components/organisms/settings/PreferencesTab.tsx
src/cloud/components/organisms/settings/SubscriptionTab.tsx
src/cloud/components/organisms/settings/TeamInfoTab.tsx
src/cloud/components/organisms/settings/UpgradeTab.tsx
src/cloud/components/organisms/settings/styled.ts

The current preferences modal too big a width for the content, so I put a container to each tab.
| ![CleanShot 2021-03-05 at 15 33 37](https://user-images.githubusercontent.com/2410692/110079163-1d1a5f00-7dcc-11eb-8ec4-dd46e8203582.png) | ![image](https://user-images.githubusercontent.com/2410692/110079480-8306e680-7dcc-11eb-8cb6-a96e6a70055a.png) |

UI: Added Container to Preferences Modal

---

src/cloud/components/organisms/ArchivedPageContent.tsx

I added `reduced-width` class to the Archived page like other pages.
| ![CleanShot 2021-03-05 at 16 39 51](https://user-images.githubusercontent.com/2410692/110083187-bac45d00-7dd1-11eb-827e-36f835606485.png) | ![CleanShot 2021-03-05 at 16 40 03](https://user-images.githubusercontent.com/2410692/110083210-c2840180-7dd1-11eb-8b3c-84e51d2e92c9.png) |

UI: Added 'reduced-width' to Archived Page

---

src/cloud/components/molecules/Editor/index.tsx
src/cloud/components/molecules/Editor/styled.ts

I adjusted the tooltip position of the scroll sync button.
| ![CleanShot 2021-03-05 at 16 49 47](https://user-images.githubusercontent.com/2410692/110086355-9cf8f700-7dd5-11eb-95b4-46cf60a78469.png) | ![CleanShot 2021-03-05 at 17 07 53](https://user-images.githubusercontent.com/2410692/110086373-a5513200-7dd5-11eb-8f35-36adcbe6678a.png) |

UI: Adjusted Tooltip Position

---

src/cloud/components/molecules/Editor/index.tsx

I restyled `StyledShortcodeConvertMenu` and made it easier to understand for the users.
| ![image](https://user-images.githubusercontent.com/2410692/110097419-5958ba00-7de2-11eb-93a3-e7711e5e726f.png) | ![CleanShot 2021-03-05 at 18 36 18](https://user-images.githubusercontent.com/2410692/110097373-4940da80-7de2-11eb-9f43-d1125c53bffd.png) |

UI: Restyled Short Code Convert Menu

---

src/cloud/components/molecules/DocTagsList/TagsAutoCompleteInput.tsx

I removed a weird text-decoration from the tags auto-complete feature.
| <img width="208" alt="Screen_Shot_2021-03-05_at_2 22 46_PM" src="https://user-images.githubusercontent.com/2410692/110099241-6d9db680-7de4-11eb-89d6-dbc0fc96e5d8.png"> | ![CleanShot 2021-03-05 at 18 53 33](https://user-images.githubusercontent.com/2410692/110099291-7abaa580-7de4-11eb-8f75-5af8a307a8da.png) |

UI: Removed Text Decoration from Tags Auto Complete

---

src/components/atoms/TagNavigatorListItem.tsx

**Fix tag color error**
When tag.data.color is set in TagNavigatorListItem the react
is throwing error that object is not extensible, in general there should be no
updating of props
Maybe there is better solution, to just assign to an object i.e. extend it somehow, but in general I think this is ok solution, since props should be in a way frozen.

Fix tag color error

---

src/cloud/components/molecules/PageHeader.tsx

I added `display: flex;` to the `PageHeader` to fix the alignment.
| ![CleanShot 2021-03-08 at 13 22 26](https://user-images.githubusercontent.com/2410692/110274262-bdad9080-8011-11eb-904d-7fbf7f5e56da.png) | ![CleanShot 2021-03-08 at 13 22 42](https://user-images.githubusercontent.com/2410692/110274282-c8682580-8011-11eb-8e97-04e21d1bf2af.png) |

UI: Fix Alignment of the Timeline Page Header

---

src/cloud/components/organisms/Modal/contents/Doc/RevisionsModal/styled.ts

I fixed the revision modal and added `overflow-y: hidden;` to `MarkdownWrapper` to show the entire content.
| ![CleanShot 2021-03-08 at 16 00 06](https://user-images.githubusercontent.com/2410692/110286834-ea20d700-8028-11eb-94f6-bfda1bda40c8.gif) | ![CleanShot 2021-03-08 at 16 00 50](https://user-images.githubusercontent.com/2410692/110286878-f86ef300-8028-11eb-855e-f6fe4d50a2fc.gif) |

UI: Fix Revision Modal Content Issue

---

src/cloud/components/organisms/DocPage/View.tsx

I adjusted the auto margin of the page content to fix the issue when it's archived.
| ![image](https://user-images.githubusercontent.com/2410692/110281848-cce80a80-8020-11eb-84ee-572bc3ec08ec.png) | ![CleanShot 2021-03-08 at 15 02 06](https://user-images.githubusercontent.com/2410692/110281884-de311700-8020-11eb-8942-c406a5eaa49d.png) |

UI: Fixed Alignment of the Archived Page Content

---

src/cloud/components/atoms/Link/AccountLink.tsx
src/cloud/components/atoms/Link/EmphasizedLink.tsx
src/cloud/components/atoms/Link/TeamLink.tsx
src/cloud/components/organisms/settings/IntegrationsTab.tsx
src/cloud/components/organisms/settings/TeamInfoTab.tsx
src/cloud/components/organisms/settings/UpgradeTab.tsx

I applied the`primaryTextColor` to the bottom links of the preferences modal to make it look more readable.
| ![CleanShot 2021-03-08 at 13 32 28](https://user-images.githubusercontent.com/2410692/110276022-9fe22a80-8015-11eb-8d00-38dd865344c0.png) | ![CleanShot 2021-03-08 at 13 36 26](https://user-images.githubusercontent.com/2410692/110276042-ae304680-8015-11eb-8e3f-d045441e7cf1.png) |
| ![CleanShot 2021-03-08 at 13 41 54](https://user-images.githubusercontent.com/2410692/110276067-bc7e6280-8015-11eb-9c39-b8c3f2497fc5.png) | ![image](https://user-images.githubusercontent.com/2410692/110276171-ecc60100-8015-11eb-91da-58eafb3888e6.png) |
| ![CleanShot 2021-03-08 at 14 00 53](https://user-images.githubusercontent.com/2410692/110276705-129 …

UI: Adjusted Link Styles in Preferences Modal

---

static/main-preload.js

Correctly handle `undefined` on mime type extraction.
This will cause corrupt attachments to be ignored.

ignore corrupt (unable to read mime type) attachments

---

src/cloud/lib/editor/hooks/useRealtime.ts

Loss of data occuring when connection is down and user reloads or closes page.
Push to cache on the `beforeunload` event

cache on page unload not just component cleanup

---

src/cloud/components/organisms/Topbar/Controls/ControlsContextMenu/DocContextMenu/index.tsx

I restyled the backlink.
- Replaced icon
- Removed underline
| ![Clipboard 2021-15-03 at 12 54 55 PM](https://user-images.githubusercontent.com/2410692/111738919-8074b880-88c5-11eb-9324-9890405c490c.png) | ![CleanShot 2021-03-19 at 15 09 07](https://user-images.githubusercontent.com/2410692/111738942-8b2f4d80-88c5-11eb-9816-74b725cecacc.png) |

UI: Restyled Backlink

---

src/components/organisms/NoteContextView.tsx
src/components/organisms/NotePageToolbar.tsx
src/lib/db/utils.ts
src/lib/exports.ts
webpack.config.ts

**Improve export consistency between HTML and PDF types** (#754)
- Add remark-admonitions for html generation
- Update metadata for html generation
- Refactor HTML export to use custom HTML generated previously for PDF only
- Refactor export functions
- Replace preferences object with actual needed preferences
- Update conversion functions for saving note document with shortcut
- Export css attachments for HTML
- Export css stylesheets
- Link css stylesheets in HTML string for HTML export
- Refactor PDF links update in markdown (remove HTML handling)
- Refactor shortcut saving HTML and Markdown
- Add saveFolder and saveName
- Update logic for production paths (use API and dev variable)
- Add katex fonts exporting and katex.min.css instead of jsdeliver link
**Error handling:**
- When …

Improve export consistency between HTML and PDF types

---

src/cloud/components/organisms/settings/MembersTab.tsx
src/cloud/components/organisms/settings/styled.ts

I added the guest count and description to the Guest menu (after upgraded) on the Members tab.
| ![CleanShot 2021-03-19 at 17 27 08](https://user-images.githubusercontent.com/2410692/111766803-4b7a5d00-88e9-11eb-90e6-2b8938c6f2ac.png) | ![CleanShot 2021-03-19 at 19 24 04](https://user-images.githubusercontent.com/2410692/111766843-546b2e80-88e9-11eb-8c5a-7c0558d5234d.png) |

UI: Added Guest Count and Description

---

src/cloud/components/atoms/LinkableHeader.tsx

Currently, when the header has a link, it won't appear when it's in preview mode. (In split view mode is fine.)
- `LinkableHeader` was causing this issue, so I fixed it.
- While doing that, I also adjusted the alignment of the link icon.
| ![CleanShot 2021-03-19 at 17 04 04](https://user-images.githubusercontent.com/2410692/111750453-98a10380-88d6-11eb-806f-6f35e8a0ba44.png) | ![image](https://user-images.githubusercontent.com/2410692/111750652-d30aa080-88d6-11eb-9783-66005d91de74.png) |

UI: Show Header with Link in Preview Mode

---

src/cloud/components/atoms/MarkdownView/styles.ts

I adjusted the styles of the embedded doc link.
- Adjusted alignment of the icons
- Adjusted spacing
| ![CleanShot 2021-03-19 at 15 19 40](https://user-images.githubusercontent.com/2410692/111740359-f548f200-88c7-11eb-9cf7-495969bb2201.png) | ![CleanShot 2021-03-19 at 19 37 19](https://user-images.githubusercontent.com/2410692/111767894-98126800-88ea-11eb-9a17-f3d5c225498e.png) |

UI: Restyled Embedded Doc Link

---

src/cloud/components/organisms/Topbar/Controls/ControlsContextMenu/DocContextMenu/index.tsx

I added height to adjust the alignment of the section header "Labels".
| ![CleanShot 2021-03-19 at 16 34 43](https://user-images.githubusercontent.com/2410692/111747380-9b015e80-88d2-11eb-8ce2-ff699c032a2d.png) | ![CleanShot 2021-03-19 at 16 43 30](https://user-images.githubusercontent.com/2410692/111747412-a2286c80-88d2-11eb-948d-8b9eeb089ead.png) |

UI: Adjusted Alignment of the "Labels"

---

src/components/atoms/MarkdownPreviewer.tsx
src/lib/exports.ts

**Add basic plantuml, mermaid and flowchart charts** (#550, #371, #678, #539)
- Add support for plantuml rendering
- Add support for charts (mermaid, flowchart)
- Add support for PDF and HTML export rendering of plantuml and mermaid
How to use it (should be the same as in cloud space, if you used it there):
Markdown to create diagrams:
[DiagramsAndCharts.txt](https://github.com/BoostIO/BoostNote.next/files/6292487/DiagramsAndCharts.txt)
**Tested in** 
- Local dev
- Production AppImage (Linux)

Add basic plantuml, mermaid and flowchart charts (local space)

---

src/components/v2/organisms/Sidebar/molecules/SidebarTree.tsx

I changed the `border-color` from `second` to `main` to make it consistent.
| ![CleanShot 2021-04-23 at 16 39 55](https://user-images.githubusercontent.com/2410692/115837047-2088a900-a453-11eb-818d-8a3ba492689d.png) | ![CleanShot 2021-04-23 at 16 42 34](https://user-images.githubusercontent.com/2410692/115837082-2a121100-a453-11eb-91ff-7da1ce1a81f8.png) |
| ![CleanShot 2021-04-23 at 16 49 00](https://user-images.githubusercontent.com/2410692/115837748-e1a72300-a453-11eb-8cad-0c94aca95f97.png) | ![CleanShot 2021-04-23 at 16 48 29](https://user-images.githubusercontent.com/2410692/115837783-ecfa4e80-a453-11eb-8b63-10bbd2c56e3d.png) |

UI: Changed the Border Color of the Sidebar

---

src/cloud/components/atoms/EditableInput.tsx
src/components/PreferencesModal/KeymapTab.tsx
src/components/PreferencesModal/PreferencesModal.tsx
src/components/atoms/CodeEditor.tsx
src/components/atoms/CustomizedCodeEditor.tsx
src/components/atoms/KeymapItemSection.tsx
src/components/organisms/NoteStorageNavigator.tsx
src/electron/index.ts
src/electron/menu.ts
src/lib/electronOnly.ts
src/lib/keymap.ts
src/lib/preferences.ts
src/locales/enUS.ts
static/main-preload.js

**Add basic keymap handling** (#752)
- Add keymap to local lite storage
- Add search keymap to app component from preferences
- Add keymap tab in preferences
- Add keymap item section
- Add keymap assign handling
- Add basic keymap UI
- Add initial keymaps
- Add handling of multiple identical shortcuts
- Add support for dynamically changing menu items accelerators
- Add initial loading of keymaps
- Add keymap loading for menu accelerators
- Add export open document shortcut customizability
How it looks now:
Error handling on duplicate shortcut key:
Demo how it behaves:
https://user-images.githubusercontent.com/18196945/113772151-99ce8f00-9724-11eb-8057-89393119efce.mp4
Todo:
- Define all customizable keymaps
- Fix clashes with shortcuts not managed with keymaps
- Add actual keymap …

Add basic keymap handling

---

src/cloud/lib/charts/charts.tsx
src/cloud/lib/charts/flowchart.tsx
src/lib/exports.ts

**Add support for chart PDF export rendering**
- Add support for Charts and FlowChart export in PDF and HTML
Markdown, PDFs, HTMLs files for testing export:
[ChartExports.zip](https://github.com/BoostIO/BoostNote.next/files/6329873/ChartExports.zip)
Preview of export:
**Tested in** 
- Local dev
- Production AppImage (Linux)

Add support for chart PDF (and HTML) export rendering (local space)

---

src/shared/components/organisms/Topbar/atoms/TopbarActionItem.tsx
src/shared/components/organisms/Topbar/atoms/TopbarTreeItem.tsx
src/shared/components/organisms/Topbar/molecules/TopbarNavigationContext.tsx

I removed `border-radius` from the context menu items on the top bar.
| ![CleanShot 2021-05-01 at 16 14 36](https://user-images.githubusercontent.com/2410692/116775026-6967df80-aa9b-11eb-894c-fae0770a84f9.png) | ![CleanShot 2021-05-01 at 16 33 03](https://user-images.githubusercontent.com/2410692/116775034-72f14780-aa9b-11eb-83e5-7e0812e6080c.png) |

UI: Removed Border Radius from Context Menu on Top Bar

---

src/components/organisms/BoostHubSignInForm.tsx

I put the local space creation button to the bottom of the page.
| <img width="1440" alt="CleanShot 2021-05-01 at 17 27 19@2x" src="https://user-images.githubusercontent.com/2410692/116776406-39243f00-aaa3-11eb-8e0f-82ecc135b980.png"> | <img width="1440" alt="CleanShot 2021-05-01 at 17 28 13@2x" src="https://user-images.githubusercontent.com/2410692/116776416-45a89780-aaa3-11eb-887b-8ab8ed2bb9b1.png"> |

UI: Adjusted Local Space Creation Button Position

---

src/cloud/components/molecules/Editor/index.tsx

Status check in out `if` causing closed comment threads to always be set outdated.

fix status check bug causing closed to always be set outdated

---

src/components/atoms/ProgressBar.tsx
src/components/molecules/ExportProgressItem.tsx
src/components/molecules/FolderNavigatorItem.tsx
src/components/molecules/StorageNavigatorFragment.tsx
src/lib/exports.ts

**Initial batch export for PDF** (#491)
- Add prepare export functions in exports.ts
- Add handling of menus for folder exports
- Add support for non-recursive/recursive exports
- Add export progress bar 
- Add support for storage/workspace export
- Refactor functions for exports
- Add component for batch export handling (state, procedure)
- Refactor folder and storage export to use the component
- Fix cancelation state logic
- Add dim background on export procedure
General functionality:
Users can export folders via the context menu.
By right-clicking on the desired folder the context menu with export options comes up:
A similar context menu dialog is available for workspace/storage navigation item (for exporting whole storage)
Once the exported is selected, the file explorer comes up …

Add batch export folder/storage in context menu 

---

src/cloud/components/organisms/Modal/contents/Workspace/WorkspaceModalForm.tsx
src/cloud/components/organisms/Modal/contents/styled.ts

- Adjusted sizing of the switch to make it look consistent with other switches
- Replaced `CustomButton` with `Button` to make it look consistent with other buttons
| ![CleanShot 2021-06-14 at 18 35 06](https://user-images.githubusercontent.com/2410692/121881744-9ec64500-cd4a-11eb-80c5-de0b34d9701d.png) | ![CleanShot 2021-06-14 at 19 53 55](https://user-images.githubusercontent.com/2410692/121881785-a980da00-cd4a-11eb-94c2-8e0256f35be7.png) |

UI: Restyled WorkspaceModalForm

---

src/cloud/components/molecules/SubscriptionForm/index.tsx
src/cloud/components/organisms/Subscription/SubscriptionManagement.tsx
src/cloud/components/organisms/settings/UpgradeTab.tsx
src/cloud/components/organisms/settings/styled.ts

- Don't transition until any necessary actions are complete.
- Display warning when possible customer actions are required.

no transition until action done & warning when action required

---

src/cloud/components/molecules/Editor/index.tsx

I added `line-height: 1.4em` to `.CodeMirror` to make all lines have the same height in the editor.

UI: Added `line-height` to `.CodeMirror`

---

src/shared/components/organisms/Sidebar/atoms/SidebarTreeForm.tsx

Add untitled as initial value in doc and folder creation input
Select whole range when initially input is opened
The feature is added to both local and cloud spaces.
Tested in cloud and local space:
Desktop app dev
Webapp dev

Add untitled as initial value in doc and folder creation input

---

src/cloud/components/molecules/Timeline/TimelineList.tsx
src/cloud/components/molecules/Timeline/TimelineListItem.tsx
src/cloud/components/organisms/Sidebar/SideNavigator/styled.ts
src/cloud/pages/[teamId]/timeline.tsx

- Removed header
- Expanded border to the edge of the section
- Put the same icon with sidenav
- Show breadcrumb above the doc title
| <img width="1348" alt="Screen Shot 2021-06-21 at 1 31 01 PM" src="https://user-images.githubusercontent.com/2410692/122760970-aa7bb380-d2d6-11eb-8835-e7030d9d96bf.png"> | ![CleanShot 2021-06-21 at 21 15 40](https://user-images.githubusercontent.com/2410692/122761012-b8c9cf80-d2d6-11eb-9f20-cdd4e66fad8b.png) |

UI: Restyled Timeline Page

---

src/components/atoms/CodeEditor.tsx
src/lib/keymap.ts

Add shortcuts to keymap for inserting date strings
- Also fix codemirror order in which shortcut is generated
- must be Shift->Ctrl/Cmd/->Alt->Key
Default shortcuts are:
`Shift+Ctrl+/` or `Shift+Cmd+/` for `macOS` - Inserts locale date (for example: `6/22/2021`)
`Ctrl+Alt+/` or `Shift+Alt+/` for `macOS` - Inserts date and time (for example: `6/22/2021, 6:47:46 PM`) 
Tested in local development mode and AppImage:
- Change keymaps to something different, test with default shortcuts
- Add locale date inside editor
- Add date and time inside editor

Add shortcuts to keymap for inserting date strings

---

src/shared/lib/dom.ts

Fix active input element condition
Without this, the active input element is not recognized and so shortcuts like `Ctrl+Shift+ArrowLeft` does jump out of editor instead of selecting the word
See this issue: #1027

Fix active input element condition

---

src/cloud/components/molecules/Banner/SubLimitReachedBanner.tsx

Since there is no limitation for team member count, so I removed the alert for that.

UI: Removed Team Member Limit Alert

---

src/cloud/components/organisms/Subscription/SubscriptionManagement.tsx

I adjusted `font-size` and `margin` of the downgrade and upgrade plan popups.
| ![CleanShot 2021-06-26 at 12 40 01](https://user-images.githubusercontent.com/2410692/123501022-27af7b80-d67d-11eb-9565-6f634186e024.png) | ![CleanShot 2021-06-26 at 12 42 05](https://user-images.githubusercontent.com/2410692/123501030-37c75b00-d67d-11eb-9995-18452da30f7d.png) |
| ![CleanShot 2021-06-26 at 12 40 20](https://user-images.githubusercontent.com/2410692/123501039-4150c300-d67d-11eb-8e60-4b9fa109bd4f.png) | ![CleanShot 2021-06-26 at 12 46 05](https://user-images.githubusercontent.com/2410692/123501047-4ca3ee80-d67d-11eb-9887-70ce8e394bcc.png) |

UI: Restyled Changing Plan Popup

---

package-lock.json
package.json
src/cloud/components/atoms/MarkdownView/index.tsx
src/cloud/components/molecules/Editor/index.tsx
src/cloud/components/molecules/TableOfContents/index.tsx
src/cloud/lib/utils/events.ts

Add linkable headers custom link
Add event for firing focus heading
Tested in dev desktop app (cloud space)
Tested in webapp (cloud space)
Workflow:
1. User creates document with headings (h1-h6 - depest level 6, can be changed later)
2. User adds toc with shortcode `[[toc]]`
2. User clicks on markdown preview links and navigates to editor heading location
3. User disables sync and clicks on links (only focuses in editor, markdown preview stays where it is)
Example:

Add initial toc component and handling in preview

---

src/cloud/components/molecules/Editor/EditorAdmonitionToolDropdown.tsx
src/cloud/components/molecules/Editor/EditorHeaderToolDropdown.tsx
src/cloud/components/molecules/Editor/index.tsx
src/cloud/components/molecules/RelativeDialog/RelativeDialog.tsx
src/cloud/components/molecules/Timeline/TimelineList.tsx
src/cloud/components/organisms/EventSource.tsx
src/cloud/components/organisms/ImportFlow/molecules/ImportFlowDestination.tsx
src/cloud/components/organisms/Modal/contents/TemplatesModal/index.tsx
src/cloud/components/organisms/Topbar/Controls/ControlsContextMenu/FolderContextMenu.tsx
src/cloud/components/organisms/Topbar/Controls/ControlsContextMenu/TagContextMenu.tsx
src/cloud/components/organisms/settings/SettingsComponent.tsx
src/cloud/components/organisms/settings/UserPreferencesForm.tsx
src/cloud/lib/i18n/enUS.ts
src/cloud/lib/i18n/fr.ts
src/cloud/lib/i18n/ja.ts
src/cloud/lib/i18n/types.ts
src/cloud/lib/i18n/zhCN.ts
src/cloud/lib/stores/settings/store.ts
src/cloud/lib/stores/settings/types.ts
src/components/App.tsx
src/mobile/components/pages/DocEditPage.tsx
src/shared/components/atoms/LeftRightList.tsx
src/shared/components/atoms/UpDownList.tsx
src/shared/components/molecules/EmojiPicker.tsx
src/shared/components/organisms/Sidebar/atoms/SidebarContextList.tsx
src/shared/components/templates/ContentLayout.tsx

Add font size and family to Account Preferences
Add translations keys and translations for all supported languages for new Settings
Update mobile and desktop app code mirror editor to respect font size and font families
Tested in desktop app
- Changing font works
- Changing font family works
- Changing languages shows correct preferences descriptions
- Changing font family loses focus after update (not sure why it happens here and not in local space)

Implement custom font settings

---

src/cloud/api/teams/docs/templates.ts
src/cloud/api/teams/resources/index.ts
src/cloud/lib/stores/nav/store.tsx

- Cancel previous nav data fetching by implementing an abort controller
- Check the abort controller again after fetching and block the update if it is already aborted. It seems there is some time gap till the browser handles aborting. So data fetching might not throw any error even if aborting is called.
- A user opens a space
- Nav hook will fetch nav data of the space
- The use navigate to another space before the data fetching is finished.
- Nav hook will fetch again for the other space.
- Now the two nav data fetchings are in race condition
- If the first data fetching is finished first, the nav data of the first space will be shown shortly in the second space page's nav
- If the second data fetching is finished first, the first data fetching will overwrite nav data so the nav data …

Cancel previous nav data fetching

---

src/cloud/lib/hooks/sidebar/useCloudSidebarSpaces.tsx

The desktop app should have sent an ipc event rather than navigating directly in a browser window(web view).
- Modified click handler of team selector so it will send ipc event in the desktop app rather than navigating in the webview.
- Hid invite menu items from the desktop app since the desktop app cannot handle the links

Fix nav team selector for desktop app

---

src/cloud/components/molecules/ContentManager/Rows/ContentManagerDocRow.tsx
src/cloud/components/molecules/ContentManager/Rows/ContentManagerFolderRow.tsx
src/cloud/components/molecules/ContentManager/Rows/ContentManagerRow.tsx
src/cloud/components/molecules/ContentManager/index.tsx
src/cloud/interfaces/resources.ts
src/cloud/lib/hooks/sidebar/useCloudDnd.ts
src/cloud/lib/hooks/sidebar/useCloudSidebarTree.tsx
src/cloud/lib/hooks/useCloudApi.ts
src/cloud/lib/utils/patterns.ts
src/shared/components/organisms/Sidebar/molecules/SidebarTree.tsx

Add dnd inside folder view and across sidenav and folder view
Add callbacks for dnd functions
Update lower level components to use dnd functions
Add initial dnd refactor
Replace dragged resource with resource saving in transfer data
Change APIs across codebase (dragStart, dragEnd, dropOn)
Add text/plain data transfer to folder and doc dragg save events
Drag and drop showcase:
https://user-images.githubusercontent.com/18196945/129209367-f6e27f3d-3cfe-44d0-9dd1-26b09e8ef716.mp4
Tested in desktop app
- Test dropping a folder inside another folder (all views, only folders view)
- Test dropping a note inside another folder
- Test dropping a note/folder from folder view to sidebar (works)
Current bug (I think already present before)
- Dropping in workspace/root folder gives already present but …

Refactor Drag and Drop and implement sidenav and folder view dragging

---

src/electron/menu.ts

Add zoom reset
Add zoom in (Ctrl++)
Add zoom out (Ctrl+-)
Remove zoom menu item in Window menu (does nothing)
Test in desktop app
Zooms out
Zooms in
Zoom reset works
Menu item 'zoom' from Window file menu removed

Add electron zoom feature

---

src/cloud/components/MarkdownView/index.tsx
src/design/components/molecules/Image/ExpandableImage.tsx
src/design/components/molecules/Image/ImagePreview.tsx
src/design/components/organisms/Modal/index.tsx
src/design/lib/stores/modal/types.ts

https://github.com/BoostIO/BoostNote.next/pull/1081

expandable image

---

src/cloud/lib/export.ts
webpack.cloud.config.ts
webpack.mobile.config.ts

Fix missing codemirror theme (default)
Fix invalid preference key in rehype pipeline for export
Add mobile and webpack cloud codemirror theme copy
Tested in desktop app
- Code block themes properly exported for HTML and shown in PDF
- Tested in Dark/White background
- Tested for different codeblock/editor themes (matching as well)
In Firefox and Chrome HTML export shows well, but PDF export in Firefox is blank (as previously), and Chrome shows weird highlighting on export (as previously).
Examples:
PDFs
[CodeBlockExportTest.pdf](https://github.com/BoostIO/BoostNote-App/files/7072536/CodeBlockExportTest.pdf)
[CodeBlockExportTest_White.pdf](https://github.com/BoostIO/BoostNote-App/files/7072537/CodeBlockExportTest_White.pdf)
HTMLs
[CodeBlockExportTest.zip](https://github.com/BoostIO/BoostNot …

Fix PDF and HTML export code block themes

---

src/cloud/components/Editor/index.tsx
src/cloud/lib/editor/CodeMirror.ts
src/mobile/components/pages/DocEditPage.tsx

Add scroll past end editor config (mobile and web/desktop)
Add scroll past end addon
Tested in desktop/web app
- Chrome
- Firefox
Showcase:
https://user-images.githubusercontent.com/18196945/131250600-d433ca54-2fba-4106-a386-dca02268b4d8.mp4

Add scroll past end

---

src/cloud/components/molecules/PageSearch/InPageSearchPortal.tsx

Add em instead of pixels
Lower distances from top and right
Showcase:

Fix in-page search location

---

src/cloud/components/Editor/index.tsx
src/cloud/components/settings/UserPreferencesForm.tsx
src/cloud/lib/i18n/enUS.ts
src/cloud/lib/i18n/fr.ts
src/cloud/lib/i18n/ja.ts
src/cloud/lib/i18n/types.ts
src/cloud/lib/i18n/zhCN.ts
src/cloud/lib/stores/settings/store.ts
src/cloud/lib/stores/settings/types.ts
src/mobile/components/pages/DocEditPage.tsx

Update mobile and basic edit page
Update preferences handling
Add show/hide option to PreferencesTab
Tested in desktop app and web app, showcase:
https://user-images.githubusercontent.com/18196945/133117996-d930eaa8-3210-459f-83e3-81a6d7278e84.mp4
Fixes: https://github.com/Boostnote/BoostHub/issues/1360
Relates to: https://github.com/BoostIO/BoostNote-App/discussions/1174

Add editor line numbers preference

---

src/cloud/components/Editor/index.tsx

Fix IME popups occluding the current line
Before fix:
After fix:
Tested in Chrome WebApp and Electron Desktop App
Showcase:
https://user-images.githubusercontent.com/18196945/133665039-08f0b2cb-3cae-4f32-be19-37047fe7d294.mp4
Didn't test on Windows but the behavior is the same on Ubuntu and Windows, and this fixes Ubuntu behavior.
Fixes: #1189
---
<details>
<summary>
</summary>
</details>

Fix IME popups occluding the current line

---

src/cloud/components/Editor/index.tsx
src/cloud/components/settings/UserPreferencesForm.tsx
src/cloud/lib/i18n/enUS.ts
src/cloud/lib/i18n/fr.ts
src/cloud/lib/i18n/ja.ts
src/cloud/lib/i18n/types.ts
src/cloud/lib/i18n/zhCN.ts
src/cloud/lib/stores/settings/store.ts
src/cloud/lib/stores/settings/types.ts

Enable spellcheck based on User Preferences in CodeMirror
Add preference for spellcheck
Add translations
Tested in Firefox and Chrome
Showcase video:
https://user-images.githubusercontent.com/18196945/133820739-d438454f-db4e-4c32-a0b5-9a38c4cdc9ce.mp4
Fixes: https://github.com/BoostIO/BoostNote-App/issues/1196

Add browser spellcheck support

---

src/cloud/api/teams/folders/index.ts
src/cloud/lib/hooks/useCloudApi.ts

Add parent folder from backend if exists, otherwise use client-side parent folder to update `'orderedIds`
Tests:
Create folders and sub-folders in private and public workspaces
Showcase:
https://user-images.githubusercontent.com/18196945/135346644-cd3343f1-37db-4870-8c1d-e7d903b0a8a8.mp4
Fixes: https://github.com/Boostnote/BoostHub/issues/1373
Combines with backend update: https://github.com/Boostnote/BoostHub/pull/1383

Add parent folder proper update on folder creation

---

src/cloud/components/DocProperties/DocDueDateSelect.tsx

Solves https://github.com/BoostIO/BoostNote-App/issues/1144
Replace icon and apply red color to the due date selector of expired documents.
---
<details>
<summary>
</summary>
This pull request has been submitted to:
- [#1144: Show outdated status of docs](https://issuehunt.io/repos/74213528/issues/1144)
---
</details>

replace icon and change color of the due date selector to outdated docs

---

package.json

**fixed this issue https://github.com/BoostIO/BoostNote-App/issues/1063.**
```
"linux": {
"icon": "static/icon.icns",
"target": [
"deb",
"rpm",
"AppImage"
]
},
```
```
"linux": {
"icon": "static/icon.icns",
"target": [
"deb",
"rpm",
"AppImage"
]
},
"rpm":{
"depends":[
"/usr/lib64/libuuid.so.1"
]
},
```
The rpm file builds correctly and works for both Fedora and Opensuse. I **built the rpm on Opensuse and Kali linux** and tried installing them in Opensuse and Fedora and they installed without any errors.  Please check the code and if you have any doubts please ping me. 
I read a lot and found out libuuid and libuuid1 both have the same files, they are just packaged with different names for Opensuse and Fedora. So I added the required file as a dependency. The rpm built on Debian systems …

fixed packaging issue for opensuse

---

src/design/components/atoms/EditableInput.tsx

Resets when text props change: previous behaviour => did not close so text/input text were mismatched

Editable Input fix 

---

src/cloud/components/MarkdownView/index.tsx

Checks for null on end variable
The make comment gutters somehow gets end = null for this markdown: 
```
<details>Hello</details>
s
j
```
The letters does not need to be exact, but 2 newlines are needed and details section above for error to show.
Showcase that it works with the fix:
Issue: https://github.com/Boostnote/BoostHub/issues/1366 (first part)

Fix make comment gutters when end is null

---

src/cloud/components/settings/UserPreferencesForm.tsx
src/cloud/lib/i18n/enUS.ts
src/cloud/lib/i18n/types.ts

Fixes #447 , Added a button for editor bottom toolbar to restore to default settings.
---
<details>
<summary>
</summary>
This pull request has been submitted to:
- [#447: Reset button at Editor Preferences](https://issuehunt.io/repos/74213528/issues/447)
---
</details>

feat(Editor): add reset editor settings button

---

src/cloud/components/FolderPage/index.tsx
src/cloud/lib/utils/iterator.ts

Changes to a folders child doc list not reflected via SSE
Child doc list was generated using out of date folder properties
Filter full docs map to generate folder child doc list based on `doc.parentFolderId`

filter full docs map on changes

---

webpack.cloud.config.ts

Webpack was configured to output filenames with `[hash]`. This was happening every hot-reload in development which caused a lot of slowdown, memory issues (as all hashed files would be retained while in --watch mode), double page refreshing and complete re-get of all files.
Solution:
Set output filename to be only based on `[name]` if `NODE_ENV === 'development'`

stop rehashing of filenames on hot-reload in dev

---

src/cloud/components/DocPage/DocPageHeader.tsx
src/cloud/components/Props/Pickers/TextSelect.tsx
src/cloud/components/Props/PropPicker.tsx
src/cloud/components/Props/PropsAddForm.tsx
src/cloud/lib/i18n/fr.ts
src/cloud/lib/i18n/ja.ts
src/cloud/lib/i18n/zhCN.ts
src/cloud/lib/props.ts

**Add text prop for doc and folder suggestions**
- Add text prop (masked as string)
- Add text prop editing (text area form input)
- Add text prop out of focus save
- Add text prop handling and icons
- Add handling of overflow for long text fields
Showcase video:
https://user-images.githubusercontent.com/18196945/144749987-878c37b7-84b6-416c-858e-f71ee24a885a.mp4
Issue: https://boostnote.io/boostio/Text-property-dC32acd35fcfaf4ff3bf871a0955305f8b

Add text prop for doc and folder suggestions

---

src/cloud/components/Views/Table/TableView.tsx
src/cloud/lib/hooks/views/tableView.ts
src/cloud/lib/views/table.ts
src/design/components/organisms/Table/Table.tsx
src/design/components/organisms/Table/atoms/TableBorderLine.tsx
src/design/components/organisms/Table/atoms/TableCell.tsx
src/design/components/organisms/Table/atoms/TableCol.tsx
src/design/components/organisms/Table/atoms/TableSlider.tsx
src/design/components/organisms/Table/tableInterfaces.ts

Add column width API update
Add column width slider which changes column width
Add Table border without change width functionality for rows
Showcase video:
https://user-images.githubusercontent.com/18196945/145294572-ae6d6d78-9e3d-4a5d-8560-f4266bb0179f.mp4
The video does not show a missing border-line for the Documents label but it has been fixed.
Currently, it does not support moving all rows just column/header row columns.
Issue: https://boostnote.io/boostio/Table:-Column-width-changes-dC3ba8baa407f24a0fb63bbec8ebb97736

Update column width changes

---

src/cloud/lib/editor/hooks/useRealtime.ts

Cache would close before teardown could flush to cache when navigating from Doc page to any other Non-Doc page
Move cache close effect to after document teardown effect

ensure cache closing runs after flush

---

src/cloud/components/FolderPage/NewFolderContextMenu.tsx
src/cloud/components/Views/index.tsx
src/cloud/components/WorkspacePage/WorkspaceContextMenu.tsx

Add query param view for smart view views
Tested with invalid queries and valid view IDs, like:
`http://localhost:3001/testspace/dashboard?view=20` after creating the views with those IDs.
Tested with folder/workspace as well:
`http://localhost:3001/testspace/Sprint-meeting-fDdf3f8586d2004bba9b1bf5df0b423ce2?view=26`
Short video showcase:
https://user-images.githubusercontent.com/18196945/148118036-847ae133-18e4-4905-8229-768518615066.mp4

Add query param view for smart view views

---

src/cloud/components/DocPage/DocContextMenuActions.tsx
src/cloud/components/DocPage/NewDocContextMenu.tsx
src/cloud/components/DocPreview/index.tsx
src/design/components/molecules/LabelManager.tsx
src/design/components/organisms/Modal/index.tsx
src/design/lib/stores/modal/store.ts
src/design/lib/stores/modal/types.ts

- Remove outdated implementation for doc context ( block editor )
- Remove href redirect in LabelsManager select
- Add doc context in preview modal
- Add button in preview
- Fix modal routing related to doc preview
- added redirect on modal change ( for when modal is replaced, is not unmounted )
- added closure event on closingAllModals
[![Image from Gyazo](https://i.gyazo.com/58a0ad0b2f0533ab941b053c8c0e2aff.gif)](https://gyazo.com/58a0ad0b2f0533ab941b053c8c0e2aff)

Doc preview - context menu

---

src/cloud/components/Comments/CommentInput.tsx
src/cloud/components/Comments/CommentList.tsx
src/cloud/components/Comments/CommentManager.tsx
src/cloud/components/Comments/ThreadActionButton.tsx
src/cloud/components/Comments/ThreadItem.tsx
src/cloud/components/Comments/ThreadList.tsx
src/cloud/components/Editor/index.tsx
src/cloud/components/MarkdownView/CustomizedMarkdownPreviewer.tsx
src/cloud/components/MarkdownView/index.tsx
src/cloud/components/UserIcon.tsx
src/cloud/lib/hooks/useCommentManagerState.ts
src/cloud/lib/hooks/useThreadMenuActions.tsx
src/cloud/lib/i18n/enUS.ts
src/mobile/components/pages/DocViewPage.tsx

Improve comment system
Remove comment from MD preview
Add comment and threads
Update comment design
Update comment inputs
Showcases:
https://user-images.githubusercontent.com/18196945/150427285-5b73b280-9cd1-4a7d-b512-d3c7f76de8df.mp4
https://user-images.githubusercontent.com/18196945/150427315-389dd4b6-fe48-4e2d-9358-63ff725d61da.mp4

Comment improvements

---

src/cloud/components/ContentManager/ContentManagerToolbar.tsx
src/cloud/components/DocPage/index.tsx
src/cloud/components/DocProperties.tsx
src/cloud/components/Modal/contents/SmartView/ConditionItem.tsx
src/cloud/components/Modal/contents/SmartView/ConditionValueControl.tsx
src/cloud/components/Props/Pickers/DocDependencySelect.tsx
src/cloud/components/Props/Pickers/PropertyValueButton.tsx
src/cloud/components/Props/Pickers/UrlSelect.tsx
src/cloud/components/Props/PropConfig.tsx
src/cloud/components/Props/PropPicker.tsx
src/cloud/components/Views/Calendar/CalendarView.tsx
src/cloud/components/Views/List/ListDocProperties.tsx
src/cloud/components/Views/Table/TableView.tsx
src/cloud/interfaces/db/props.ts
src/cloud/interfaces/db/smartView.ts
src/cloud/lib/hooks/props/index.ts
src/cloud/lib/hooks/useCloudDocPreview.tsx
src/cloud/lib/hooks/useCloudResourceModals.tsx
src/cloud/lib/props.ts
src/cloud/lib/smartViews.ts
src/cloud/lib/stores/nav/store.tsx
src/cloud/lib/stores/nav/types.ts
src/cloud/lib/views/table.ts
src/design/components/molecules/Form/atoms/FormSelect.tsx
src/lib/string.ts
src/mobile/components/molecules/ContentManagerDocRow.tsx
src/mobile/components/molecules/ContentManagerRowLinkContent.tsx
src/mobile/components/organisms/ContentManager.tsx

- Remove JSON type and fix interfaces
- fix some typescript issues
- Add new URL property interface & UI
- Fix old timeperiod URL property implementation ( interface & UI )
- Add new DocDependency Property ( interface & UI )

Doc properties - compound & url

---

src/cloud/components/Views/EditableDocItemContainer.tsx
src/cloud/components/Views/EditableItemContainer.tsx
src/cloud/components/Views/Kanban/Item.tsx
src/cloud/components/Views/List/index.tsx
src/cloud/components/Views/Table/TableView.tsx
src/cloud/lib/i18n/enUS.ts
src/cloud/lib/i18n/fr.ts
src/cloud/lib/i18n/ja.ts
src/cloud/lib/i18n/types.ts
src/cloud/lib/i18n/zhCN.ts
src/design/components/atoms/EditableInput.tsx

Add editable item to Kanban, List, and Table
https://user-images.githubusercontent.com/18196945/152247227-cc254134-523b-436a-a118-f783f9913c53.mp4

Add editable item component for all views

---

src/cloud/components/Automations/FilterBuilder.tsx
src/design/components/molecules/Form/atoms/FormSelect.tsx

- Reset filter type select too.
It seems React Select cannot recognize `undefined`. So I had to use `null`

Reset filter type after adding

---

src/cloud/api/teams/docs/exports.ts
src/cloud/components/DocPage/DocContextMenuActions.tsx
src/cloud/lib/client.ts

PDF exporting was sending data as JSON(Binary->Uint8Array-> JSON number array) which is very inefficient.
Now, the server send raw data only and the app download it without any extra processing

Handle blob directly

---

src/cloud/components/Props/Pickers/UrlSelect.tsx

Add open selector when URL is empty or invalid
Showcase:
https://user-images.githubusercontent.com/18196945/159187026-3aa25154-2238-45ad-88ab-5c00b6221f4e.mp4

Improve URL select for URL prop

---

src/cloud/components/Editor/index.tsx
src/cloud/components/MarkdownView/CustomizedMarkdownPreviewer.tsx
src/cloud/components/MarkdownView/MarkdownCheckbox.tsx
src/cloud/components/MarkdownView/index.tsx
src/cloud/lib/hooks/editor/docEditor.ts
src/mobile/components/pages/DocEditPage.tsx

Update editor ref update content to feature scroll into view for previous cursor position
Showcase (same as in local)
cc: https://github.com/BoostIO/BoostNote.next-local/pull/69
https://user-images.githubusercontent.com/18196945/159185293-24f32ce6-a87c-4198-b240-c5db218a0c28.mp4

Update markdown preview checkbox update handling

---

src/cloud/lib/stores/search/store.ts

Calling `.forEach` on `undefined` error in search history
Malformed search history was being un-serialized as `undefined` rather than an `Array`
Only update history state if loaded cache data is an `Array`

protect against malformed (non-array) cached search history

---

src/cloud/lib/stores/pageStore/store.tsx

Breadcrumbs would show only last visited workspace on every page.
Merging new `pageProps` into existing would not remove old `page{Doc|Folder|Workspace}` if it was a page transition.
Remove old `page{Doc|Folder|Workspace}` if `page{Doc|Folder|Workspace}` exists in new merge data

remove page{Doc|Folder|Workspace} if exists in pageProps merge data

---

src/cloud/api/pages/teams/index.ts

Non-workspaces pages have incorrect breadcrumbs on initial load
Bulk team data call includes a `pageWorkspace` overriding the `page{Doc|Folder}` prop in breadcrumb resolution
Explicitly set `pageWorkspace` to `undefined` in page data return.

explicitly set pageWorkspace to undefined for non-workspace pages
